---
title: "V0 Monitoring Report"
output:
  html_document:
    toc: true
    theme: cerulean
date: '`r Sys.time()`'
---

```{r, echo=FALSE, message=FALSE}
library(reactable)
library(data.table)
library(dplyr)
library(htmltools)
library(glue)
library(fontawesome)
```


```{r, echo = FALSE, message=FALSE}
render_report_table <- function(data, element_id, output_filename){
  onclick_command <- glue::glue(
    "Reactable.downloadDataCSV('{element_id}', '{output_filename}')")
  htmltools::browsable(
  tagList(
    tags$button(
      tagList(fontawesome::fa("download"), "Download as CSV"),
      onclick = onclick_command
    ),
    
    reactable(data,
            defaultColDef = colDef(
    header = function(value) gsub(".", " ", value, fixed = TRUE),
    cell = function(value) format(value, nsmall = 1),
    align = "center",
    minWidth = 70,
    headerStyle = list(background = "#f7f7f8")
  ),
  columns = list(
    Species = colDef(minWidth = 140)  # overrides the default
  ),
    bordered = TRUE,
    highlight = TRUE,
    filterable = TRUE,
    elementId = element_id
  )
  )
)
}
```


## V0 Monitoring: 
```{r, echo = FALSE, message=FALSE}
data <- fread('clean_form/sev0.csv') %>% 
  tibble::as_tibble(.name_repair = 'unique')


# by HH
hh_cnt <- data %>%
  dplyr::group_by(community_health_unit) %>%
  dplyr::summarise(
    target_num_hh = 470,
    target_num_hh_headcount = 580
  )

# by safety status
icf_eos_completed <- data %>% 
  dplyr::group_by(community_health_unit) %>%
  dplyr::summarise(
    visit_num_hh = 55,
    visit_num_hh_headcount = 800
  )


# by absences
absences <- data %>% 
  dplyr::group_by(community_health_unit) %>%
  dplyr::summarise(
    absences_num_hh = 55,
    absences_num_indiv = 800
  )

joined_data <- hh_cnt %>% 
  dplyr::inner_join(icf_eos_completed, by = 'community_health_unit') %>% 
  dplyr::inner_join(absences, by = 'community_health_unit') %>% 
  dplyr::mutate(
    visit_num_hh_perc_plan = visit_num_hh / target_num_hh,
    visit_num_hh_headcount_perc_plan = visit_num_hh_headcount / target_num_hh_headcount,
    absences_num_hh_perc_plan = absences_num_hh / target_num_hh,
    absences_num_indiv_perc_plan = absences_num_indiv / target_num_hh_headcount) %>%
  dplyr::select(
    community_health_unit,
    target_num_hh,
                target_num_hh_headcount,
                visit_num_hh, 
                visit_num_hh_perc_plan,
                visit_num_hh_headcount,
                visit_num_hh_headcount_perc_plan,
                absences_num_hh,
                absences_num_hh_perc_plan,
                absences_num_indiv,
                absences_num_indiv_perc_plan
    )
```

```{r, echo=FALSE,message=FALSE}
reactable(
  joined_data,
  columns = list(
    community_health_unit = colDef(
      name = "Community Health Unit",
      filterable = TRUE, 
      filterMethod = JS("function(rows, columnId, filterValue) {
        return rows.filter(function(row) {
          return row.values[columnId].indexOf(filterValue) !== -1
        })
      }"), sticky = 'left'),
    target_num_hh = colDef(name = "Household"),
    target_num_hh_headcount = colDef(name = "Household Members"),
    visit_num_hh = colDef(name = "Household"),
    visit_num_hh_perc_plan = colDef(
      name = '%',
      format = colFormat(percent = TRUE, digits = 1),
          style = function(value) {
      if (value > 1) {
        color <- "#008000"
      } else if (value < 1) {
        color <- "#e00000"
      } else {
        color <- "#777"
      }
      list(color = color, fontWeight = "bold")
    }),
    visit_num_hh_headcount = colDef(name = "Household Members"),
    visit_num_hh_headcount_perc_plan = colDef(
      name = '%',
      format = colFormat(percent = TRUE, digits = 1),
                style = function(value) {
      if (value > 1) {
        color <- "#008000"
      } else if (value < 1) {
        color <- "#e00000"
      } else {
        color <- "#777"
      }
      list(color = color, fontWeight = "bold")
    }),
    absences_num_hh = colDef(name = "Household"),
    absences_num_hh_perc_plan = colDef(
      name = '%',
      format = colFormat(percent = TRUE, digits = 1),
          style = function(value) {
      if (value > 1) {
        color <- "#008000"
      } else if (value < 1) {
        color <- "#e00000"
      } else {
        color <- "#777"
      }
      list(color = color, fontWeight = "bold")
    }),
    absences_num_indiv = colDef(name = "Individual"),
    absences_num_indiv_perc_plan = colDef(
      name = '%',
      format = colFormat(percent = TRUE, digits = 1),
                style = function(value) {
      if (value > 1) {
        color <- "#008000"
      } else if (value < 1) {
        color <- "#e00000"
      } else {
        color <- "#777"
      }
      list(color = color, fontWeight = "bold")
    })
  ),
  columnGroups = list(
    colGroup(name = "Target", 
             columns = c("target_num_hh", "target_num_hh_headcount")),
    colGroup(name = "Visits", 
             columns = c("visit_num_hh", 
                         "visit_num_hh_perc_plan",
                         "visit_num_hh_headcount",
                         "visit_num_hh_headcount_perc_plan",
                         "absences_num_hh",
                         "absences_num_hh_perc_plan",
                         "absences_num_indiv",
                         "absences_num_indiv_perc_plan"
                         ))
  ),
    bordered = TRUE,
    highlight = TRUE
)
```


<!-- ## Ento Monitoring Form 3: Light Trap Mosquito Collections -->
<!-- This section covers all the recruitment and withdrawals for Ento Forms -->

<!-- Purpose: -->

<!-- - Summarising mosquito numbers\n -->

<!-- - Monitoring the target buffer and core household per collection\n method   -->
<!-- - Monitoring No. of mosquitoes used for dissection\n -->

<!-- ### Ento Monitoring Form 3A: Household in Core and Buffer -->
<!-- ```{r, echo = FALSE, message=FALSE} -->
<!-- data <- fread( -->
<!--   'clean_form/ento_monitoring_light_trap_households.csv') %>% -->
<!--   dplyr::select( -->
<!--     `Cluster` = cluster, -->
<!--     `Month` = month_date, -->
<!--     `Collection Site` = collection_site, -->
<!--     `No. of forms submitted from buffer` = num_hh_submitted_from_buffer, -->
<!--     `No. of forms submitted from core` = num_hh_submitted_from_core) -->


<!-- render_report_table( -->
<!--   data,  -->
<!--   element_id = "ento-download-light-trap-household", -->
<!--   output_filename = "report_ento_monitoring_light_trap_households.csv") -->
<!-- ``` -->

<!-- ### Ento Monitoring Form 3B: Number of Mosquitoes Dissected for Parity -->
<!-- ```{r, echo = FALSE, message=FALSE} -->
<!-- data <- fread( -->
<!--   'clean_form/ento_monitoring_light_trap_dissected_for_parity.csv') %>% -->
<!--   dplyr::select( -->
<!--     `Cluster` = cluster, -->
<!--     `Month` = month_date, -->
<!--     `Arm` = arm, -->
<!--     `No. of Mosquitoes Dissected for Parity` = num_dissected_for_parity) -->


<!-- render_report_table( -->
<!--   data,  -->
<!--   element_id = "ento-download-light-trap-dissected", -->
<!--   output_filename = "report_ento_monitoring_light_trap_dissected_for_parity.csv") -->
<!-- ``` -->
