---
title: "Ento Monitoring Report"
output:
  html_document:
    toc: true
    theme: cerulean
date: '`r Sys.time()`'
---

```{r, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(
  comment = '', 
  echo = FALSE,
  message = FALSE,
  cache=FALSE
)
```


```{r, echo=FALSE, message=FALSE}
library(reactable)
library(data.table)
library(dplyr)
library(htmltools)
library(glue)
library(fontawesome)
library(cloudbrewr)
library(lubridate)
```


```{r}
# create log messages
logger::log_info('Extract Screening Form')

# create directory
output_dir <-'tmp'
unlink(output_dir, recursive = TRUE)
dir.create(output_dir)

# variables / creds for ento
env_pipeline_stage <- Sys.getenv("PIPELINE_STAGE")
input_bucket <- 'databrew.org'
output_bucket <- 'bohemia-lake-db'
input_key <- list(
  screening = 'kwale/clean-form/entoscreeningke/entoscreeningke.csv',
  mosquito = 'kwale/clean-form/entoltmorphid/entoltmorphid.csv',
  resting = 'kwale/clean-form/entorcmorphid/entorcmorphid.csv'
)

tryCatch({
  logger::log_info('Attempt AWS login')
  # login to AWS - this will be bypassed if executed in CI/CD environment
  cloudbrewr::aws_login(
    role_name = 'cloudbrewr-aws-role',
    profile_name =  'cloudbrewr-aws-role',
    pipeline_stage = env_pipeline_stage)

}, error = function(e){
  logger::log_error('AWS Login Failed')
  stop(e$message)
})
```
```{r}
# Read from ento cluster asset (@joebrew)
ento_clusters <- fread('assets/ento_clusters.csv') %>%
  dplyr::mutate(cluster = sprintf("%02.0f", cluster_number))

# Form Monitoring 1 Recruitment and Withdrawals
data <- cloudbrewr::aws_s3_get_table(
  bucket = input_bucket,
  key = input_key$screening) %>%
  dplyr::filter(
    site != "Larval Habitat")

orig_les <- data %>%
  dplyr::filter(orig_le != "") %>% .$orig_le
orig_hhid <- data %>%
  dplyr::filter(orig_hhid != "") %>% .$orig_hhid
le_data <- data %>%
  dplyr::filter(leid != "") %>%
  dplyr::select(id = leid,
                orig_le,
                todays_date,
                site,
                village,
                Longitude,
                Latitude,
                geo_cluster_num) %>%
  dplyr::mutate(
    id = as.character(id),
    orig_le = as.character(orig_le),
    todays_date = lubridate::date(todays_date),
    id_type = 'livestock_enclosure',
    id = as.character(id)
  )
hh_data <- data %>%
  dplyr::filter(hhid != "") %>%
  dplyr::select(id = hhid,
                orig_hhid,
                todays_date,
                site,
                village,
                Longitude,
                Latitude, 
                geo_cluster_num) %>%
  dplyr::mutate(
    id = as.character(id),
    orig_hhid = as.character(orig_hhid),
    todays_date = lubridate::date(todays_date),
    id_type = 'household',
    id = as.character(id)
)

base_tbl <- dplyr::bind_rows(le_data, hh_data) %>% 
  dplyr::mutate(cluster_number = geo_cluster_num)

##########################################
# create tables here
##########################################

# Form Monitoring 1: Recruitment and Withdrawals
withdrawals <- base_tbl %>%
  dplyr::filter(orig_le != "" | orig_hhid != "") %>%
  dplyr::mutate(active_or_withdrawn = 'withdrawn',
                date_of_withdrawal = todays_date)

active <- base_tbl %>%
  dplyr::anti_join(withdrawals, by = 'id') %>%
  dplyr::mutate(active_or_withdrawn = 'active',
                date_of_withdrawal = NA_Date_)

monitoring_tbl_base <- dplyr::bind_rows(active, withdrawals) %>%
  dplyr::mutate(id = as.character(id))

output_filename <- glue::glue('{output_dir}/summary_ento_recruitment_withdrawal.csv')
monitoring_tbl <- monitoring_tbl_base %>%
  dplyr::select(
    cluster_number,
    id,
    date_of_consent = todays_date,
    collection_method = site,
    active_or_withdrawn,
    date_of_withdrawal) %>%
  distinct() %>%
  tidyr::drop_na(cluster_number)

monitoring_tbl %>%
  fwrite(output_filename)

cloudbrewr::aws_s3_store(
  bucket = output_bucket,
  key = 'bohemia_prod/summary_ento_recruitment_withdrawal/summary_ento_recruitment_withdrawal.csv',
  filename = as.character(output_filename)
)


# Form Monitoring 2: ICF List
s3_catalog <- cloudbrewr::aws_s3_get_catalog(bucket = output_bucket)
output_filename <- glue::glue('{output_dir}/summary_ento_icf_list.csv')
stg_key <- 'bohemia_stg/manual_adjustment_ento_icf_list/manual_adjustment_ento_icf_list.csv'
prod_key <- 'bohemia_prod/summary_ento_icf_list/summary_ento_icf_list.csv'

# check if there is manual upload in staging bucket
# if none, create a new table with all nulls
if(!stg_key %in% unique(s3_catalog$key)){
  monitoring_icf <- monitoring_tbl %>%
    dplyr::select(cluster_number,
                  id,
                  date_of_consent) %>%
    dplyr::mutate(
      name_of_person_receiving_in_field = NA_character_,
      date_of_person_receiving_in_field = NA_character_,
      name_of_person_receiving_in_office = NA_character_,
      date_of_person_receiving_in_office = NA_character_,
      name_of_archivist_receiving = NA_character_,
      date_of_archivist_receiving = NA_character_
    )
# if there is manual uploads in staging, create a join to table
}else{
  monitoring_ifc_from_upload <- cloudbrewr::aws_s3_get_table(
    bucket = output_bucket,
    key = stg_key) %>%
    dplyr::select(
      cluster_number = `Cluster`,
      id = `Household ID / Livestock Enclosure ID`,
      date_of_consent = `Date of consent on screening form`,
      name_of_person_receiving_in_field = `Name of Person Receiving in the Field`,
      date_of_person_receiving_in_field =`Date of Field Receival`,
      name_of_person_receiving_in_office = `Name of Person Receiving in the Office`,
      date_of_person_receiving_in_office = `Date of Office Receival`,
      name_of_archivist_receiving = `Name of Archivist Receiving` ,
      date_of_archivist_receiving = `Date of Archivist Receival`
    ) %>%
    dplyr::mutate(
      cluster_number = as.character(cluster_number),
      id = as.character(id),
      date_of_consent = lubridate::date(date_of_consent),
      date_of_person_receiving_in_field = lubridate::date(date_of_person_receiving_in_field),
      date_of_person_receiving_in_office = lubridate::date(date_of_person_receiving_in_office),
      date_of_archivist_receiving = lubridate::date(date_of_archivist_receiving)
    )

  monitoring_icf <- monitoring_tbl %>%
    dplyr::select(cluster_number, id, date_of_consent) %>%
    dplyr::inner_join(
      monitoring_ifc_from_upload,
      by = c('cluster_number','id', 'date_of_consent'))
}


monitoring_icf %>%
  fwrite(output_filename)
cloudbrewr::aws_s3_store(
  bucket = output_bucket,
  key = 'bohemia_prod/summary_ento_icf_list/summary_ento_icf_list.csv',
  filename = as.character(output_filename)
)

```


```{r, echo = FALSE, message=FALSE}
render_report_table <- function(data, element_id, output_filename){
  onclick_command <- glue::glue(
    "Reactable.downloadDataCSV('{element_id}', '{output_filename}')")
  htmltools::browsable(
  tagList(
    tags$button(
      tagList(fontawesome::fa("download"), "Download as CSV"),
      onclick = onclick_command
    ),
    
    reactable(data,
            defaultColDef = colDef(
    header = function(value) gsub(".", " ", value, fixed = TRUE),
    cell = function(value) format(value, nsmall = 1),
    align = "center",
    minWidth = 70,
    headerStyle = list(background = "#f7f7f8")
  ),
  columns = list(
    Species = colDef(minWidth = 140)  # overrides the default
  ),
    bordered = TRUE,
    highlight = TRUE,
    filterable = TRUE,
    elementId = element_id
  )
  )
)
}
```


## Ento Monitoring Form 1: Recruitment & Withdrawals
To be used for site reporting on enrolment progress active and withdrawn households 

```{r , echo = FALSE, message=FALSE}
monitoring0 <- cloudbrewr::aws_s3_get_table(
  bucket = 'bohemia-lake-db',
  key = 'bohemia_prod/summary_ento_recruitment_withdrawal/summary_ento_recruitment_withdrawal.csv'
)

monitoring1 <- monitoring0 %>%
  dplyr::select(`Cluster` = cluster_number,
                `Household ID / Livestock Enclosure ID` = id,
                `Date of consent on screening form` = date_of_consent,
                `Collection Method` = collection_method,
                `Active or Withdrawn` = active_or_withdrawn,
                `Date of Withdrawal on the screening form` = date_of_withdrawal)

render_report_table(
  monitoring1, 
  element_id = "ento-download-recruitment-withdrawals",
  output_filename = "report_ento_monitoring_hh_recruitment_withdrawal.csv")
```

## Ento Monitoring Form 2: ICF List
To be used to track the number of ICFs expected from houses recorded as consented on the screening form and to track handover of ICFs

```{r}
monitoring_icf <- cloudbrewr::aws_s3_get_table(
  bucket = 'bohemia-lake-db',
  key = 'bohemia_prod/summary_ento_icf_list/summary_ento_icf_list.csv') %>%
  dplyr::select(`Cluster` = cluster_number,
                `Household ID / Livestock Enclosure ID` = id,
                `Date of consent on screening form` = date_of_consent,
                `Name of Person Receiving in the Field` = name_of_person_receiving_in_field,
                `Date of Field Receival` = date_of_person_receiving_in_field,
                `Name of Person Receiving in the Office` = name_of_person_receiving_in_office,
                `Date of Office Receival` = date_of_person_receiving_in_office,
                `Name of Archivist Receiving` = name_of_archivist_receiving,
                `Date of Archivist Receival` = date_of_archivist_receiving)

render_report_table(
  monitoring_icf, 
  element_id = "ento-download-icf-list",
  output_filename = "summary_ento_icf_list.csv")
```


<!-- ## Ento Monitoring Form 3: Light Trap Mosquito Collections -->
<!-- This section covers all the recruitment and withdrawals for Ento Forms -->

<!-- Purpose: -->

<!-- - Summarising mosquito numbers\n -->

<!-- - Monitoring the target buffer and core household per collection\n method   -->
<!-- - Monitoring No. of mosquitoes used for dissection\n -->

<!-- ### Ento Monitoring Form 3A: Household in Core and Buffer -->
<!-- ```{r, echo = FALSE, message=FALSE} -->
<!-- data <- fread( -->
<!--   'clean_form/ento_monitoring_light_trap_households.csv') %>% -->
<!--   dplyr::select( -->
<!--     `Cluster` = cluster, -->
<!--     `Month` = month_date, -->
<!--     `Collection Site` = collection_site, -->
<!--     `No. of forms submitted from buffer` = num_hh_submitted_from_buffer, -->
<!--     `No. of forms submitted from core` = num_hh_submitted_from_core) -->


<!-- render_report_table( -->
<!--   data,  -->
<!--   element_id = "ento-download-light-trap-household", -->
<!--   output_filename = "report_ento_monitoring_light_trap_households.csv") -->
<!-- ``` -->

<!-- ### Ento Monitoring Form 3B: Number of Mosquitoes Dissected for Parity -->
<!-- ```{r, echo = FALSE, message=FALSE} -->
<!-- data <- fread( -->
<!--   'clean_form/ento_monitoring_light_trap_dissected_for_parity.csv') %>% -->
<!--   dplyr::select( -->
<!--     `Cluster` = cluster, -->
<!--     `Month` = month_date, -->
<!--     `Arm` = arm, -->
<!--     `No. of Mosquitoes Dissected for Parity` = num_dissected_for_parity) -->


<!-- render_report_table( -->
<!--   data,  -->
<!--   element_id = "ento-download-light-trap-dissected", -->
<!--   output_filename = "report_ento_monitoring_light_trap_dissected_for_parity.csv") -->
<!-- ``` -->
