---
title: "Ento Monitoring Report"
output:
  html_document:
    toc: true
    theme: cerulean
date: '`r Sys.time()`'
---

```{r, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(
  comment = '', 
  echo = FALSE,
  message = FALSE,
  cache=FALSE
)
```


```{r, echo=FALSE, message=FALSE}
library(reactable)
library(data.table)
library(dplyr)
library(htmltools)
library(glue)
library(fontawesome)
```


```{r, echo = FALSE, message=FALSE}
render_report_table <- function(data, element_id, output_filename){
  onclick_command <- glue::glue(
    "Reactable.downloadDataCSV('{element_id}', '{output_filename}')")
  htmltools::browsable(
  tagList(
    tags$button(
      tagList(fontawesome::fa("download"), "Download as CSV"),
      onclick = onclick_command
    ),
    
    reactable(data,
            defaultColDef = colDef(
    header = function(value) gsub(".", " ", value, fixed = TRUE),
    cell = function(value) format(value, nsmall = 1),
    align = "center",
    minWidth = 70,
    headerStyle = list(background = "#f7f7f8")
  ),
  columns = list(
    Species = colDef(minWidth = 140)  # overrides the default
  ),
    bordered = TRUE,
    highlight = TRUE,
    filterable = TRUE,
    elementId = element_id
  )
  )
)
}
```


## Ento Monitoring Form 1: Recruitment & Withdrawals
To be used for site reporting on enrolment progress active and withdrawn households 

```{r , echo = FALSE, message=FALSE}
monitoring0 <- cloudbrewr::aws_s3_get_table(
  bucket = 'bohemia-lake-db',
  key = 'bohemia_prod/summary_ento_recruitment_withdrawal/summary_ento_recruitment_withdrawal.csv'
)

monitoring1 <- monitoring0 %>%
  dplyr::select(`Cluster` = cluster_number,
                `Household ID / Livestock Enclosure ID` = id,
                `Date of consent on screening form` = date_of_consent,
                `Collection Method` = collection_method,
                `Active or Withdrawn` = active_or_withdrawn,
                `Date of Withdrawal on the screening form` = date_of_withdrawal)

render_report_table(
  monitoring1, 
  element_id = "ento-download-recruitment-withdrawals",
  output_filename = "report_ento_monitoring_hh_recruitment_withdrawal.csv")
```

## Ento Monitoring Form 2: ICF List
To be used to track the number of ICFs expected from houses recorded as consented on the screening form and to track handover of ICFs

```{r}
monitoring_icf <- cloudbrewr::aws_s3_get_table(
  bucket = 'bohemia-lake-db',
  key = 'bohemia_prod/summary_ento_icf_list/summary_ento_icf_list.csv') %>%
  dplyr::select(`Cluster` = cluster_number,
                `Household ID / Livestock Enclosure ID` = id,
                `Date of consent on screening form` = date_of_consent,
                `Name of Person Receiving in the Field` = name_of_person_receiving_in_field,
                `Date of Field Receival` = date_of_person_receiving_in_field,
                `Name of Person Receiving in the Office` = name_of_person_receiving_in_office,
                `Date of Office Receival` = date_of_person_receiving_in_office,
                `Name of Archivist Receiving` = name_of_archivist_receiving,
                `Date of Archivist Receival` = date_of_archivist_receiving)

render_report_table(
  monitoring_icf, 
  element_id = "ento-download-icf-list",
  output_filename = "summary_ento_icf_list.csv")
```


<!-- ## Ento Monitoring Form 3: Light Trap Mosquito Collections -->
<!-- This section covers all the recruitment and withdrawals for Ento Forms -->

<!-- Purpose: -->

<!-- - Summarising mosquito numbers\n -->

<!-- - Monitoring the target buffer and core household per collection\n method   -->
<!-- - Monitoring No. of mosquitoes used for dissection\n -->

<!-- ### Ento Monitoring Form 3A: Household in Core and Buffer -->
<!-- ```{r, echo = FALSE, message=FALSE} -->
<!-- data <- fread( -->
<!--   'clean_form/ento_monitoring_light_trap_households.csv') %>% -->
<!--   dplyr::select( -->
<!--     `Cluster` = cluster, -->
<!--     `Month` = month_date, -->
<!--     `Collection Site` = collection_site, -->
<!--     `No. of forms submitted from buffer` = num_hh_submitted_from_buffer, -->
<!--     `No. of forms submitted from core` = num_hh_submitted_from_core) -->


<!-- render_report_table( -->
<!--   data,  -->
<!--   element_id = "ento-download-light-trap-household", -->
<!--   output_filename = "report_ento_monitoring_light_trap_households.csv") -->
<!-- ``` -->

<!-- ### Ento Monitoring Form 3B: Number of Mosquitoes Dissected for Parity -->
<!-- ```{r, echo = FALSE, message=FALSE} -->
<!-- data <- fread( -->
<!--   'clean_form/ento_monitoring_light_trap_dissected_for_parity.csv') %>% -->
<!--   dplyr::select( -->
<!--     `Cluster` = cluster, -->
<!--     `Month` = month_date, -->
<!--     `Arm` = arm, -->
<!--     `No. of Mosquitoes Dissected for Parity` = num_dissected_for_parity) -->


<!-- render_report_table( -->
<!--   data,  -->
<!--   element_id = "ento-download-light-trap-dissected", -->
<!--   output_filename = "report_ento_monitoring_light_trap_dissected_for_parity.csv") -->
<!-- ``` -->
