---
title: "Efficacy Status Report"
output: 
  html_document:
    toc: true
    theme: cerulean
date: '`r Sys.time()`'
---

Notes:

- Report is refreshed hourly 9-5pm EAT, once 12AM EAT
- Please reach out to nikamgorski@gmail.com for bug reports


```{r, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(
  comment = '', 
  echo = FALSE,
  message = FALSE,
  cache=FALSE,
  warning=FALSE
)
```

```{r setup, include=FALSE}
### PURPOSE:
# This code aims to determine who is out, refusal, in, and eos after efficacy. This information comes from Safety, Safetynew, and Absence1stattempt. Then for each status (except of in), split each status into the "reason" or the "how" they got to that status.
# load required libraries
library(dplyr)
library(reactable)
library(data.table)
library(cloudbrewr)
library(fontawesome)
library(shiny)

ENV_PIPELINE_STAGE <- Sys.getenv("PIPELINE_STAGE")
DATA_STAGING_BUCKET_NAME <- 'databrew.org'
DATA_LAKE_BUCKET_NAME <- 'bohemia-lake-db'
PROJECT_SOURCE <- 'kwale'
SE_FOLDER_TARGET <- glue::glue('{PROJECT_SOURCE}/clean-form')

pad_hhid <- function(data){
  if('hhid' %in% names(data)){
    data %>%
      dplyr::mutate(hhid = stringr::str_pad(hhid, 5, pad = "0"))
  }else{
    data
  }
}


tryCatch({
  logger::log_info('Attempt AWS login')
  # login to AWS - this will be bypassed if executed in CI/CD environment
  cloudbrewr::aws_login(
    role_name = 'cloudbrewr-aws-role',
    profile_name =  'cloudbrewr-aws-role',
    pipeline_stage = ENV_PIPELINE_STAGE)

}, error = function(e){
  logger::log_error('AWS Login Failed')
  stop(e$message)
})


# load in the data
absence1stattempt <- cloudbrewr::aws_s3_get_table(
  bucket = DATA_STAGING_BUCKET_NAME,
  key = glue::glue('{PROJECT_SOURCE}/sanitized-form/absences1stattempt/absences1stattempt.csv')) %>%
  pad_hhid()

v0_dem_repeat <- cloudbrewr::aws_s3_get_table(
    bucket = DATA_STAGING_BUCKET_NAME,
    key = glue::glue('{PROJECT_SOURCE}/sanitized-form/v0demography/v0demography-repeat_individual.csv')) %>%
    pad_hhid()

v0_demography <- cloudbrewr::aws_s3_get_table(
    bucket = DATA_STAGING_BUCKET_NAME,
    key = glue::glue('{PROJECT_SOURCE}/sanitized-form/v0demography/v0demography.csv')) %>%
    pad_hhid()

efficacy <- cloudbrewr::aws_s3_get_table(
  bucket = DATA_STAGING_BUCKET_NAME,
  key = glue::glue('{PROJECT_SOURCE}/sanitized-form/efficacy/efficacy.csv')) %>%
  pad_hhid()

safety <- cloudbrewr::aws_s3_get_table(
  bucket = DATA_STAGING_BUCKET_NAME,
  key = glue::glue('{PROJECT_SOURCE}/sanitized-form/safety/safety.csv')) %>%
  pad_hhid()

safetynew <- cloudbrewr::aws_s3_get_table(
  bucket =DATA_STAGING_BUCKET_NAME,
  key = glue::glue('{PROJECT_SOURCE}/sanitized-form/safetynew/safetynew.csv')) %>%
  pad_hhid()

safety_repeat_individual <- cloudbrewr::aws_s3_get_table(
  bucket = DATA_STAGING_BUCKET_NAME,
  key = glue::glue('{PROJECT_SOURCE}/sanitized-form/safety/safety-repeat_individual.csv')) %>%
  pad_hhid()

safetynew_repeat_individual <- cloudbrewr::aws_s3_get_table(
  bucket =DATA_STAGING_BUCKET_NAME,
  key = glue::glue('{PROJECT_SOURCE}/sanitized-form/safetynew/safetynew-repeat_individual.csv')) %>%
  pad_hhid()

efficacy_targets <- cloudbrewr::aws_s3_get_table(
  bucket ='bohemia-lake-db',
  key = glue::glue('bohemia_prod/dwh/goal_efficacy_targets/goal_efficacy_targets.csv')) %>%
  pad_hhid()

# this is a function to create a download csv button
wrap_download <- function(reactable_obj, element_id, output_filename){
  onclick_command <- glue::glue(
    "Reactable.downloadDataCSV('{element_id}', '{output_filename}')")
  htmltools::browsable(
    tagList(
      tags$button(
        tagList(fontawesome::fa("download"), "Download as CSV"),
        onclick = onclick_command),
      reactable_obj
    ))
}
```

```{r data creation}
# create the merged v0 data
  v0dem <- left_join(v0_dem_repeat, v0_demography, by=c('PARENT_KEY' = 'KEY'))  %>%
    select(extid, dob, sex, todays_date) %>%
    rename(dob_v0 = dob,
           todays_date_v0 = todays_date,
           sex_v0 = sex)

# include efficacy information
  eff <- efficacy %>%
    rename(dob_efficacy = dob,
           sex_efficacy = sex, 
           todays_date_efficacy = todays_date) %>%
    mutate(efficacy_reason = case_when(
      efficacy_status == 'in' ~ 'in',
      not_continue_eos == '1' ~ 'decline participation',
      not_agree_efficacy_procedures_eos == '1' ~ 'not agree to efficacy procedures',
      non_resident_eos == '1' ~ 'not a resident',
      other_trials_eos == '1' ~ 'enrolled in other trials',
      person_absent_reason_eos == '1' | person_absent == '1' ~ 'absent',
      person_unenrolled_migrated == '1' ~ 'migrated',
      person_unenrolled_died == '1' ~ 'died',
      thumbprint_status == '0' ~ 'thumbprint status',
      sign_icf_status == '0' ~ 'sign icf status',
      minor_assent_status == '0' ~ 'minor assent status',
      starting_efficacy_status == 'eos' ~ 'previously eos',
      TRUE ~ NA_character_  # To handle cases that don't match any condition
    )) #%>%
    #select(visit, extid, efficacy_status, dob_efficacy, todays_date_efficacy, sex_efficacy, efficacy_reason)
  
# create the dataset that will be used for this script
  # this will exclude the people who were manually removed
  data <- left_join(v0dem, eff, by = c('extid')) %>%
    filter(extid != '74052-06', # dob change led to not efficacy eligible (aka out of 5-15 years)
           extid != '18039-03', # "
           extid != '02042-03', # "
           extid != '02042-02', # "
           extid != '26007-03', # "
           extid != '56118-06') # "
  
# create the dataset for the extid explorer
  data_investigation <- data %>%
    filter(!is.na(visit)) %>% # removes extids not in Efficacy
    select(visit, extid, efficacy_status, efficacy_reason, sex_v0, sex_efficacy, dob_v0, dob_efficacy, todays_date_v0, todays_date_efficacy)
```

```{r targets}
# these numbers are determined by Aryton based on Joe's logic and are stored in AWS
target_table <- efficacy_targets %>%
  group_by(visit) %>%
  summarise(hh_target = sum(hh_target),
            ind_target = sum(ind_target))

# identify how many households were visited in V1 and V2
total_efficacy <- efficacy %>%
  group_by(visit) %>%
  summarise(hh_visited = n_distinct(hhid),
            ind_visited = n_distinct(extid))

# join the number of households visited and targets
target_table <- left_join(target_table, total_efficacy, by = c('visit'))

target_table <- target_table %>%
  select(visit, ind_target, ind_visited, hh_target, hh_visited) %>%
  rename(Visit = visit,
         'Individual target' = ind_target,
         'Individual visited' = ind_visited,
         'HH target' = hh_target,
         'HH visited' = hh_visited)
```

```{r total}
## this will create the table of how many people are in, out, refusal, or eos in efficacy v1

# only take the necessary columns from efficacy
total_efficacy <- data %>%
  select(KEY, extid, visit, safety_status, efficacy_status)

# since this is only a table for V1 we will only keep V1 people
total_efficacy_v1 <- total_efficacy %>%
  filter(visit == 'V1')

  # create a summary table of efficacy_status counts
  # P.S. the efficacy v1 target was determined based on a file received from Joe
  total_efficacy_status_v1 <- total_efficacy_v1 %>%
    group_by(efficacy_status) %>%
    summarise('Number of people visited in V1' = n()) %>%
    arrange(efficacy_status) %>%
    rename('Efficacy status' = efficacy_status) %>%
    add_row('Efficacy status' = 'total people visited', 'Number of people visited in V1' = sum(.$'Number of people visited in V1')) %>%
    mutate('Percent complete' = (as.numeric(`Number of people visited in V1`)) / as.numeric(nrow(total_efficacy_v1)) * 100) %>%
    mutate('Percent complete' = round(`Percent complete`, 2)) %>%
    mutate('Percent complete' = paste0(`Percent complete`, '%'))

# totals for V2
total_efficacy_v2 <- data %>%
  filter(visit == 'V2')

  total_efficacy_status_v2 <- total_efficacy_v2 %>%
      group_by(efficacy_status) %>%
      summarise('Number of people visited in V2' = n()) %>%
      arrange(efficacy_status) %>%
      rename('Efficacy status' = efficacy_status) %>%
      add_row('Efficacy status' = 'total people visited', 'Number of people visited in V2' = sum(.$'Number of people visited in V2')) %>%
      mutate('Percent complete' = (as.numeric(`Number of people visited in V2`)) / as.numeric(nrow(total_efficacy_v2)) * 100) %>%
      mutate('Percent complete' = round(`Percent complete`, 2)) %>%
      mutate('Percent complete' = paste0(`Percent complete`, '%'))
```

```{r in}
## create a table of how many people are in as enrolment and in as follow up in Efficacy V2
# create a dataset with the in efficacy status people from Efficacy V2 and then joining Efficacy V1 and V2 (total_safety_v1 and total_safety_v2)
efficacy_v2 <- total_efficacy_v2 %>%
  rename(v2_efficacystatus = efficacy_status,
         v2_efficacyreason = efficacy_reason) %>%
  select(extid, v2_efficacystatus, v2_efficacyreason) # get the v2 'in' people

efficacy_v2 <- left_join(efficacy_v2, total_efficacy_v1, by=c('extid')) %>%
  select(extid, efficacy_status, v2_efficacystatus, v2_efficacyreason) %>%
  rename(v1_efficacystatus = efficacy_status) %>% # join the v2 'in' people with their v1 statuses
  mutate(visit_type = case_when( # create a column that says whether the safety people are follow up or enrolment.
    v1_efficacystatus == 'in' ~ 'follow up',
    v1_efficacystatus == 'out' |
      is.na(v1_efficacystatus) ~ 'enrolment'
  ))

efficacy_v2_in <- efficacy_v2 %>%
  filter(v2_efficacystatus == 'in')

# create a table that shows how many people are follow up and enrolment in V2
# make a table of reasons people are eos
in_type_v2 <- efficacy_v2_in %>%
  group_by(visit_type) %>%
  summarise('Number of in people' = n()) %>%
  arrange(visit_type) %>%
  rename('Visit type' = visit_type) %>%
  add_row('Visit type' = 'total in', 'Number of in people' = sum(.$'Number of in people')) %>%
  mutate('Percent' = (as.numeric(`Number of in people`)) / as.numeric(nrow(efficacy_v2_in)) * 100) %>%
  mutate('Percent' = round(`Percent`, 2)) %>%
  mutate('Percent' = paste0(`Percent`, '%')) # Replace zero values with NA
```

```{r eos}
## this will create a table of how many people are eos and why they are eos

## V1 ############################# 
  efficacy_eos_v1 <- data %>%
    filter(visit == 'V1',
           efficacy_status == 'eos')
  
  # make a table of why people are eos
  eos_reasons_v1 <- efficacy_eos_v1 %>%
    group_by(efficacy_reason) %>%
    summarise('Number of eos people' = n()) %>%
    arrange(efficacy_reason) %>%
    rename('Reason for eos' = efficacy_reason) %>%
    add_row('Reason for eos' = 'total visited', 'Number of eos people' = sum(.$'Number of eos people')) %>%
    mutate('Percent complete' = (as.numeric(`Number of eos people`)) / as.numeric(nrow(efficacy_eos_v1)) * 100) %>%
    mutate('Percent complete' = round(`Percent complete`, 2)) %>%
    mutate('Percent complete' = paste0(`Percent complete`, '%')) # Replace zero values with NA
  

## V2 ########################### # need to add enrolment vs. follow up
  
  efficacy_eos_v2 <- efficacy_v2 %>%
    filter(v2_efficacystatus == 'eos')
  
  # make a table of why people are eos
  eos_reasons_v2 <- efficacy_eos_v2 %>%
    group_by(v2_efficacyreason) %>%
    summarise('Number of eos people' = n()) %>%
    arrange(v2_efficacyreason) %>%
    rename('Reason for eos' = v2_efficacyreason) %>%
    add_row('Reason for eos' = 'total visited', 'Number of eos people' = sum(.$'Number of eos people')) %>%
    mutate('Percent complete' = (as.numeric(`Number of eos people`)) / as.numeric(nrow(efficacy_eos_v2)) * 100) %>%
    mutate('Percent complete' = round(`Percent complete`, 2)) %>%
    mutate('Percent complete' = paste0(`Percent complete`, '%')) # Replace zero values with NA

# create datasets to make an enrolment and follow up eos table
  total_eff_eos_enrolment_v2 <- efficacy_eos_v2 %>%
    filter(visit_type == 'enrolment')
  total_eff_eos_followup_v2 <- efficacy_eos_v2 %>%
    filter(visit_type == 'follow up')
  
# make a table of enrolment people who are eos
  eos_reasons_enrolment_v2 <- total_eff_eos_enrolment_v2 %>%
    group_by(v2_efficacyreason) %>%
    summarise('Number of eos people' = n()) %>%
    arrange(v2_efficacyreason) %>%
    rename('Reason for eos' = v2_efficacyreason) %>%
    add_row('Reason for eos' = 'total visited', 'Number of eos people' = sum(.$'Number of eos people')) %>%
    mutate('Percent complete' = (as.numeric(`Number of eos people`)) / as.numeric(nrow(total_eff_eos_enrolment_v2)) * 100) %>%
    mutate('Percent complete' = round(`Percent complete`, 2)) %>%
    mutate('Percent complete' = paste0(`Percent complete`, '%')) # Replace zero values with NA

# make a table of reasons follow up people are eos #
  eos_reasons_followup_v2 <- total_eff_eos_followup_v2 %>%
    group_by(v2_efficacyreason) %>%
    summarise('Number of eos people' = n()) %>%
    arrange(v2_efficacyreason) %>%
    rename('Reason for eos' = v2_efficacyreason) %>%
    add_row('Reason for eos' = 'total visited', 'Number of eos people' = sum(.$'Number of eos people')) %>%
    mutate('Percent complete' = (as.numeric(`Number of eos people`)) / as.numeric(nrow(total_eff_eos_followup_v2)) * 100) %>%
    mutate('Percent complete' = round(`Percent complete`, 2)) %>%
    mutate('Percent complete' = paste0(`Percent complete`, '%')) # Replace zero values with NA

```

```{r out}
## this will create a table of how many people are out and why they are out

## V1 ########################### 
  efficacy_out_v1 <- data %>%
    filter(visit == 'V1',
           efficacy_status == 'out')
  
  out_reasons_v1 <- efficacy_out_v1 %>%
    group_by(efficacy_reason) %>%
    summarise('Number of out people' = n()) %>%
    arrange(efficacy_reason) %>%
    rename('Reason for out' = efficacy_reason) %>%
    add_row('Reason for out' = 'total visited', 'Number of out people' = sum(.$'Number of out people')) %>%
    mutate('Percent complete' = (as.numeric(`Number of out people`)) / as.numeric(nrow(efficacy_out_v1)) * 100) %>%
    mutate('Percent complete' = round(`Percent complete`, 2)) %>%
    mutate('Percent complete' = paste0(`Percent complete`, '%')) # Replace zero values with NA
   
## V2 ##############################
  
  efficacy_out_v2 <- data %>%
    filter(visit == 'V2',
           efficacy_status == 'out')
  
    # make a table of why people are out
  out_reasons_v2 <- efficacy_out_v2 %>%
    group_by(efficacy_reason) %>%
    summarise('Number of out people' = n()) %>%
    arrange(efficacy_reason) %>%
    rename('Reason for out' = efficacy_reason) %>%
    add_row('Reason for out' = 'total visited', 'Number of out people' = sum(.$'Number of out people')) %>%
    mutate('Percent complete' = (as.numeric(`Number of out people`)) / as.numeric(nrow(efficacy_out_v2)) * 100) %>%
    mutate('Percent complete' = round(`Percent complete`, 2)) %>%
    mutate('Percent complete' = paste0(`Percent complete`, '%')) # Replace zero values with NA
  
```

```{r refusal}
## this will create a table of how many people are refusal and why they are refusal

## V1 ########################### 
  efficacy_refusal_v1 <- data %>%
    filter(visit == 'V1',
           efficacy_status == 'refusal')
  
  refusal_reasons_v1 <- efficacy_refusal_v1 %>%
    group_by(efficacy_reason) %>%
    summarise('Number of refusal people' = n()) %>%
    arrange(efficacy_reason) %>%
    rename('Reason for refusal' = efficacy_reason) %>%
    add_row('Reason for refusal' = 'total visited', 'Number of refusal people' = sum(.$'Number of refusal people')) %>%
    mutate('Percent complete' = (as.numeric(`Number of refusal people`)) / as.numeric(nrow(efficacy_refusal_v1)) * 100) %>%
    mutate('Percent complete' = round(`Percent complete`, 2)) %>%
    mutate('Percent complete' = paste0(`Percent complete`, '%')) # Replace zero values with NA
   
## V2 ##############################
  
  efficacy_refusal_v2 <- data %>%
    filter(visit == 'V2',
           efficacy_status == 'refusal')
  
  refusal_reasons_v2 <- efficacy_refusal_v2 %>%
    group_by(efficacy_reason) %>%
    summarise('Number of refusal people' = n()) %>%
    arrange(efficacy_reason) %>%
    rename('Reason for refusal' = efficacy_reason) %>%
    add_row('Reason for refusal' = 'total visited', 'Number of refusal people' = sum(.$'Number of refusal people')) %>%
    mutate('Percent complete' = (as.numeric(`Number of refusal people`)) / as.numeric(nrow(efficacy_refusal_v2)) * 100) %>%
    mutate('Percent complete' = round(`Percent complete`, 2)) %>%
    mutate('Percent complete' = paste0(`Percent complete`, '%')) # Replace zero values with NA
```

```{r rdt-results}
eff_results <- efficacy %>%
  select(extid, cluster, pan_result, pf_result, visit, efficacy_status) %>%
  mutate(combination = case_when(pan_result == 'Positive' & pf_result == 'Positive' ~ 'pan + pf +',
                                 pan_result == 'Negative' & pf_result == 'Negative' ~ 'pan - pf -',
                                 pan_result == 'Positive' & pf_result == 'Negative' ~ 'pan + pf -',
                                 pan_result == 'Negative' & pf_result == 'Positive' ~ 'pan - pf +',
                                 pan_result == '' & pf_result == '' ~ 'blank test responses'))

eff_results_v1 <- eff_results %>%
  filter(visit == 'V1', 
         efficacy_status == 'in')

# make combination into individual columns
eff_results_v1_edited <- eff_results_v1 %>%
  mutate(
    neg_pos = ifelse(pan_result == 'Negative' & pf_result == 'Positive', 1, 0),
    pos_neg = ifelse(pan_result == 'Positive' & pf_result == 'Negative', 1, 0),
    pos_pos = ifelse(pan_result == 'Positive' & pf_result == 'Positive', 1, 0),
    neg_neg = ifelse(pan_result == 'Negative' & pf_result == 'Negative', 1, 0)
  )

# Using the four combinations of test possibilities (pan+/-;pf+/-), create a table by cluster which is downloadable.
eff_cluster_rdt_results_v1 <- eff_results_v1_edited %>%
  group_by(cluster) %>%
  summarise('pan+ pf+' = sum(pos_pos),
            'pan+ pf-' = sum(pos_neg),
            'pan- pf+' = sum(neg_pos),
            'pan- pf-' = sum(neg_neg)) %>%
  rename(Cluster = cluster)

# we want to see the rates of malaria. So create a table of totals (all clusters) of the proportions of the four ways using (pan+/-;pf+/-). Include percentages of each for the entire study.
eff_results_v1_clean <- eff_results_v1 %>%
  filter(combination != 'blank test responses')

eff_rdt_prop_totals_v1 <- eff_results_v1_clean %>%
  group_by(combination) %>%
  summarise('Count' = n()) %>%
  add_row(combination = 'total children', 'Count' = sum(.$'Count')) %>%
  mutate(Percent = (as.numeric(`Count`)) / as.numeric(nrow(eff_results_v1_clean)) * 100) %>%
  mutate(Percent = round(Percent, 2)) %>%
  mutate(Percent = paste0(Percent, '%')) %>%
  rename('Combination type' = combination)


## V2 ##############################

eff_results_v2 <- eff_results %>%
  filter(visit == 'V2', 
         efficacy_status == 'in')

# make combination into individual columns
eff_results_v2_edited <- eff_results_v2 %>%
  mutate(
    neg_pos = ifelse(pan_result == 'Negative' & pf_result == 'Positive', 1, 0),
    pos_neg = ifelse(pan_result == 'Positive' & pf_result == 'Negative', 1, 0),
    pos_pos = ifelse(pan_result == 'Positive' & pf_result == 'Positive', 1, 0),
    neg_neg = ifelse(pan_result == 'Negative' & pf_result == 'Negative', 1, 0)
  )

# Using the four combinations of test possibilities (pan+/-;pf+/-), create a table by cluster which is downloadable.
eff_cluster_rdt_results_v2 <- eff_results_v2_edited %>%
  group_by(cluster) %>%
  summarise('pan+ pf+' = sum(pos_pos),
            'pan+ pf-' = sum(pos_neg),
            'pan- pf+' = sum(neg_pos),
            'pan- pf-' = sum(neg_neg)) %>%
  rename(Cluster = cluster)

# we want to see the rates of malaria. So create a table of totals (all clusters) of the proportions of the four ways using (pan+/-;pf+/-). Include percentages of each for the entire study.
eff_results_v2_clean <- eff_results_v2 %>%
  filter(combination != 'blank test responses')

eff_rdt_prop_totals_v2 <- eff_results_v2_clean %>%
  group_by(combination) %>%
  summarise('Count' = n()) %>%
  add_row(combination = 'total children', 'Count' = sum(.$'Count')) %>%
  mutate(Percent = (as.numeric(`Count`)) / as.numeric(nrow(eff_results_v2_clean)) * 100) %>%
  mutate(Percent = round(Percent, 2)) %>%
  mutate(Percent = paste0(Percent, '%')) %>%
  rename('Combination type' = combination)
```

## Efficacy targets
```{r target_show}
reactable(target_table, columns = list(), pagination = FALSE)
```

## V2 Numbers
```{r v2_total_show}
reactable(total_efficacy_status_v2, columns = list(
  `Percent complete` = colDef(align = 'right')
))

# make a note of duplicates
if (any(duplicated(total_efficacy_v2$extid))) {
  cat('Note: Excluding the duplicates, the real total number of people visited is',
      length(unique(total_efficacy_v2$extid)), '.\n')
} else {
  cat("Note: There are no duplicates based on extid in the data.")
}
```

### in
```{r in_show}
reactable(in_type_v2, columns = list(
  `Percent` = colDef(align = 'right')
), pagination = FALSE) #pagination makes the entire table show on one page
```

### eos
```{r v2_eos_show}
reactable(eos_reasons_v2, columns = list(
  `Percent complete` = colDef(align = 'right')
), pagination = FALSE) #pagination makes the entire table show on one page

# generate a message that says which reasons do not appear
# Specify the names you want to check for
names_to_check <- c('decline participation', 
                    'not agree to efficacy procedures', 
                    'not a resident', 
                    'enrolled in other trials')

# Initialize a vector to store names not found
not_found_names <- character(0)

# Check each name
for (name in names_to_check) {
  if (!name %in% efficacy_eos_v2$efficacy_reason) {
    not_found_names <- c(not_found_names, name)
  }
}

# Generate a message based on the results (only if names are not found)
if (length(not_found_names) > 0) {
  cat("The following are not reasons for eos:", paste0(not_found_names, collapse = " / ", "."))
}
```

#### follow up visit
```{r v2_eos_followup_show}

reactable(eos_reasons_followup_v2, columns = list(
  `Percent complete` = colDef(align = 'right')
), pagination = FALSE) #pagination makes the entire table show on one page

```

#### enrolment visit
```{r v2_eos_enrolment}

reactable(eos_reasons_enrolment_v2, columns = list(
  `Percent complete` = colDef(align = 'right')
), pagination = FALSE) #pagination makes the entire table show on one page

```


### out
```{r v2_out_show}
reactable(out_reasons_v2, columns = list(
  `Percent complete` = colDef(align = 'right')
), pagination = FALSE) #pagination makes the entire table show on one page

# generate a message that says which reasons do not appear
# Specify the names you want to check for
names_to_check <- c('migrated', 
                    'died', 
                    'absent',
                    'not enrolled yet')

# Initialize a vector to store names not found
not_found_names <- character(0)

# Check each name
for (name in names_to_check) {
  if (!name %in% efficacy_out_v2$efficacy_reason) {
    not_found_names <- c(not_found_names, name)
  }
}

# Generate a message based on the results (only if names are not found)
if (length(not_found_names) > 0) {
  cat("The following are not reasons for out status:", paste0(not_found_names, collapse = " / ", "."))
}
```

### refusal
```{r v2_refusal_show}
reactable(refusal_reasons_v2, columns = list(
  `Percent complete` = colDef(align = 'right')
), pagination = FALSE) #pagination makes the entire table show on one page

# generate a message that says which reasons do not appear
# Specify the names you want to check for
names_to_check <- c('thumbprint status', 
                    'sign icf status', 
                    'minor assent status')

# Initialize a vector to store names not found
not_found_names <- character(0)

# Check each name
for (name in names_to_check) {
  if (!name %in% efficacy_refusal_v2$efficacy_reason) {
    not_found_names <- c(not_found_names, name)
  }
}

# Generate a message based on the results (only if names are not found)
if (length(not_found_names) > 0) {
  cat("The following are not reasons for refusals:", paste0(not_found_names, collapse = "/ ", "."))
}
```

###  rdt results
#### total rdt results in v2
```{r rdt-results-totals-v2}
reactable(eff_rdt_prop_totals_v2, columns = list(
  `Percent` = colDef(align = 'right')
), pagination = FALSE) #pagination makes the entire table show on one page

# make a note of blank test responses
if (sum(eff_results_v2$combination == 'blank test responses') >= 1) {
  cat('Note:', sum(eff_results_v2$combination == 'blank test responses'), 'blank test responses have been excluded from this table.\n')
} else {
  cat('Note: No blank test responses were recorded.\n')
}
```

#### rdt results by cluster in v2
```{r rdt-results-by-cluster-v2}
element_id <- 'efficacy-rdt-results-by-cluster-v2'

eff_cluster_rdt_results_readable <- reactable(eff_cluster_rdt_results_v2, columns = list(), 
                                              highlight = TRUE,
                                              resizable = TRUE,
                                              bordered = TRUE,
                                              striped = TRUE,
                                              filterable=TRUE,
                                              elementId = element_id
                                              )

wrap_download(
  eff_cluster_rdt_results_readable, 
  element_id,
  'efficacy_rdt_results_by_cluster.csv')
```


## V1 Numbers
```{r v1_total_show}
reactable(total_efficacy_status_v1, columns = list(
  `Percent complete` = colDef(align = "right")
))

# make a note of the real total number of people visited without repeats
if (any(duplicated(total_efficacy_v1$extid))) {
  cat("Note: Excluding the duplicates, the real total number of people visited is", length(unique(total_efficacy_v1$extid)), "\n.")
} else {
  cat("Note: There are no duplicates based on extid in the data.")
}
```

### eos
```{r v1_eos_show}
reactable(eos_reasons_v1, columns = list(
  `Percent complete` = colDef(align = 'right')
), pagination = FALSE) #pagination makes the entire table show on one page

# because the table is organised by extid and not reason, some reasons may not appear on the table; therefore the next part will create a line of code that generates a message that says which reason is not appearing. In this by names I mean the reason column.
# Specify the names you want to check for
names_to_check <- c('decline participation', 'not agree to efficacy procedures', 'not a resident', 'enrolled in other trials')

# Initialize a vector to store names not found
not_found_names <- character(0)

# Check each name
for (name in names_to_check) {
  if (!name %in% efficacy_eos_v1$efficacy_reason) {
    not_found_names <- c(not_found_names, name)
  }
}

# Generate a message based on the results (only if names are not found)
if (length(not_found_names) > 0) {
  cat("The following reasons are not reasons for eos status:", paste0(not_found_names, collapse = " / ", "."))
}
```

### out
```{r v1_out_show}
reactable(out_reasons_v1, columns = list(
  `Percent complete` = colDef(align = 'right')
), pagination = FALSE) #pagination makes the entire table show on one page

# because the table is organised by extid and not reason, some reasons may not appear on the table; therefore the next part will create a line of code that generates a message that says which reason is not appearing. In this by names I mean the reason column.
# Specify the names you want to check for
names_to_check <- c('migrated', 'died', 'absent')

# Initialize a vector to store names not found
not_found_names <- character(0)

# Check each name
for (name in names_to_check) {
  if (!name %in% efficacy_out_v1$efficacy_reason) {
    not_found_names <- c(not_found_names, name)
  }
}

# Generate a message based on the results (only if names are not found)
if (length(not_found_names) > 0) {
  cat("The following reasons are not reasons for out status:", paste0(not_found_names, collapse = ", ", "."))
}
```

### refusal
```{r v1_refusal_show}
reactable(refusal_reasons_v1, columns = list(
  `Percent complete` = colDef(align = 'right')
), pagination = FALSE) #pagination makes the entire table show on one page

# because the table is organised by extid and not reason, some reasons may not appear on the table; therefore the next part will create a line of code that generates a message that says which reason is not appearing. In this by names I mean the reason column.
# Specify the names you want to check for
names_to_check <- c('thumbprint status', 'sign icf status', 'minor assent status')

# Initialize a vector to store names not found
not_found_names <- character(0)

# Check each name
for (name in names_to_check) {
  if (!name %in% efficacy_refusal_v1$efficacy_reason) {
    not_found_names <- c(not_found_names, name)
  }
}

# Generate a message based on the results (only if names are not found)
if (length(not_found_names) > 0) {
  cat("The following are not reasons for refusals:", paste0(not_found_names, collapse = ", ", "."))
}
```

###  rdt results
#### total rdt results in v1
```{r rdt-results-totals-v1}
reactable(eff_rdt_prop_totals_v1, columns = list(
  `Percent` = colDef(align = 'right')
), pagination = FALSE) #pagination makes the entire table show on one page

# make a note of blank test responses
if (sum(eff_results_v1$combination == 'blank test responses') >= 1) {
  cat('Note:', sum(eff_results_v1$combination == 'blank test responses'), 'blank test responses have been excluded from this table.\n')
} else {
  cat('Note: No blank test responses were recorded. \n')
}

```

#### rdt results by cluster in v1
```{r rdt-results-by-cluster-v1}
element_id <- 'efficacy-rdt-results-by-cluster-v1'

eff_cluster_rdt_results_readable <- reactable(eff_cluster_rdt_results_v1, columns = list(), 
                                              highlight = TRUE,
                                              resizable = TRUE,
                                              bordered = TRUE,
                                              striped = TRUE,
                                              filterable=TRUE,
                                              elementId = element_id
                                              )

wrap_download(
  eff_cluster_rdt_results_readable, 
  element_id,
  'efficacy_rdt_results_by_cluster.csv')
```

## extid explorer
```{r extid-explorer}
element_id <- 'extid-explorerer'

data_readable <- reactable(data_investigation, columns = list(), 
                                              highlight = TRUE,
                                              resizable = TRUE,
                                              bordered = TRUE,
                                              striped = TRUE,
                                              filterable=TRUE,
                                              elementId = element_id
                                              )

wrap_download(
  data_readable, 
  element_id,
  'efficacy_extid_explorer.csv')
```