---
title: "PFU Report"
output: 
  html_document:
    toc: true
    theme: cerulean
date: '`r Sys.time()`'
---

Notes:

- Report is refreshed hourly 9-5pm EAT, once 12AM EAT
- Please reach out to nikamgorski@gmail.com for bug reports


```{r, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(
  comment = '', 
  echo = FALSE,
  message = FALSE,
  cache=FALSE,
  warning=FALSE
)
```

```{r setup, include=FALSE}
### PURPOSE:
# determine how many woman had submissions for PFU; enter only as in and only thing that can happen is become EOS. So interesting to know how many submissions and out of this how many are in and EOS and of EOS why EOS (miscarriage, abortion, etc.) ~ look at Paula's dm about this below.
# 1. Dead, migrated 2. Does not confirm 3. Absent 4 times on a row: LTFU (lost to follow up) 4. No longer pregnant; If not: What happened? □ Baby was born alive □ Miscarriage/loss of baby (no visible baby or less than 5 months since last menstrual period) □ Abortion (self-induced) □ Baby was born dead □ Prefer not to answer

# load required libraries
library(dplyr)
library(reactable)
library(data.table)
library(cloudbrewr)
library(fontawesome)
library(shiny)
library(ggplot2)
library(tidyr)

ENV_PIPELINE_STAGE <- Sys.getenv("PIPELINE_STAGE")
DATA_STAGING_BUCKET_NAME <- 'databrew.org'
DATA_LAKE_BUCKET_NAME <- 'bohemia-lake-db'
PROJECT_SOURCE <- 'kwale'
SE_FOLDER_TARGET <- glue::glue('{PROJECT_SOURCE}/clean-form')

pad_hhid <- function(data){
  if('hhid' %in% names(data)){
    data %>%
      dplyr::mutate(hhid = stringr::str_pad(hhid, 5, pad = "0"))
  }else{
    data
  }
}


tryCatch({
  logger::log_info('Attempt AWS login')
  # login to AWS - this will be bypassed if executed in CI/CD environment
  cloudbrewr::aws_login(
    role_name = 'cloudbrewr-aws-role',
    profile_name =  'cloudbrewr-aws-role',
    pipeline_stage = ENV_PIPELINE_STAGE)

}, error = function(e){
  logger::log_error('AWS Login Failed')
  stop(e$message)
})


# load in the data
pfu <- cloudbrewr::aws_s3_get_table(
  bucket = DATA_STAGING_BUCKET_NAME,
  key = glue::glue('{PROJECT_SOURCE}/sanitized-form/pfu/pfu.csv')) %>%
  pad_hhid()

pfu_repeat <- cloudbrewr::aws_s3_get_table(
  bucket = DATA_STAGING_BUCKET_NAME,
  key = glue::glue('{PROJECT_SOURCE}/sanitized-form/pfu/pfu-repeat_preg_symptom.csv')) %>%
  pad_hhid()

v0_dem_repeat <- cloudbrewr::aws_s3_get_table(
    bucket = DATA_STAGING_BUCKET_NAME,
    key = glue::glue('{PROJECT_SOURCE}/sanitized-form/v0demography/v0demography-repeat_individual.csv')) %>%
    pad_hhid()

v0_demography <- cloudbrewr::aws_s3_get_table(
    bucket = DATA_STAGING_BUCKET_NAME,
    key = glue::glue('{PROJECT_SOURCE}/sanitized-form/v0demography/v0demography.csv')) %>%
    pad_hhid()

pfu_targets <- cloudbrewr::aws_s3_get_table(
  bucket ='bohemia-lake-db',
  key = glue::glue('bohemia_prod/dwh/goal_pfu_targets/goal_pfu_targets.csv')) %>%
  pad_hhid()

# this is a function to create a download csv button
wrap_download <- function(reactable_obj, element_id, output_filename){
  onclick_command <- glue::glue(
    "Reactable.downloadDataCSV('{element_id}', '{output_filename}')")
  htmltools::browsable(
    tagList(
      tags$button(
        tagList(fontawesome::fa("download"), "Download as CSV"),
        onclick = onclick_command),
      reactable_obj
    ))
}
```

```{r targets}
# these numbers are determined by Aryton based on Joe's logic and are stored in AWS
  target_table <- pfu_targets %>%
    group_by(visit) %>%
    summarise(hh_target = sum(hh_target),
              ind_target = sum(ind_target))

# identify how many households were visited in V1 and V2
visited <- pfu %>%
  group_by(visit) %>%
  summarise(hh_visited = n_distinct(hhid),
            ind_visited = n_distinct(extid))

# join the number of households visited and targets
target_table <- left_join(target_table, visited, by = c('visit'))

target_table <- target_table %>%
  select(visit, ind_target, ind_visited, hh_target, hh_visited) %>%
  rename(Visit = visit,
         'Individual target' = ind_target,
         'Individual visited' = ind_visited,
         'HH target' = hh_target,
         'HH visited' = hh_visited)
```

```{r status}
# make a table of the number of women in, eos, and total visited for each visit

## V2 ###############
  pfu_v2 <- pfu %>%
    filter(visit == 'V2') 
  
  # change Status from logical to character
  pfu_v2$Status <- as.character(pfu_v2$Status)

  pfu_totals_v2 <- pfu_v2 %>%
      group_by(pregnancy_status) %>%
      summarise('number of people visited' = n()) %>%
      arrange(pregnancy_status) %>%
      rename('PFU status' = pregnancy_status) %>%
      add_row('PFU status' = 'total people visited', 
              'number of people visited' = sum(.$'number of people visited')) %>%
      mutate('Percent complete' = (as.numeric(`number of people visited`)) / as.numeric(nrow(pfu_v2)) * 100) %>%
      mutate('Percent complete' = round(`Percent complete`, 2)) %>%
      mutate('Percent complete' = paste0(`Percent complete`, '%'))
  
  
## V3 ########################
  pfu_v3 <- pfu %>%
    filter(visit == 'V3') 

  # change Status from logical to character
  pfu_v3$Status <- as.character(pfu_v3$Status)

  pfu_totals_v3 <- pfu_v3 %>%
      group_by(pregnancy_status) %>%
      summarise('number of people visited' = n()) %>%
      arrange(pregnancy_status) %>%
      rename('PFU status' = pregnancy_status) %>%
      add_row('PFU status' = 'total people visited', 
              'number of people visited' = sum(.$'number of people visited')) %>%
      mutate('Percent complete' = (as.numeric(`number of people visited`)) / as.numeric(nrow(pfu_v3)) * 100) %>%
      mutate('Percent complete' = round(`Percent complete`, 2)) %>%
      mutate('Percent complete' = paste0(`Percent complete`, '%'))
  
  
## V4 ########################
  pfu_v4 <- pfu %>%
    filter(visit == 'V4') 

  # change Status from logical to character
  pfu_v4$Status <- as.character(pfu_v4$Status)

  pfu_totals_v4 <- pfu_v4 %>%
      group_by(pregnancy_status) %>%
      summarise('Number of people visited in V4 (target: ?)' = n()) %>%
      arrange(pregnancy_status) %>%
      rename('PFU status' = pregnancy_status) %>%
      add_row('PFU status' = 'total people visited', 
              'Number of people visited in V4 (target: ?)' = sum(.$'Number of people visited in V4 (target: ?)')) %>%
      mutate('Percent complete' = (as.numeric(`Number of people visited in V4 (target: ?)`)) / as.numeric(nrow(pfu_v4)) * 100) %>%
      mutate('Percent complete' = round(`Percent complete`, 2)) %>%
      mutate('Percent complete' = paste0(`Percent complete`, '%'))
  
  
## V5 ########################
  pfu_v5 <- pfu %>%
    filter(visit == 'V5') 

  # change Status from logical to character
  pfu_v5$Status <- as.character(pfu_v5$Status)

  pfu_totals_v5 <- pfu_v5 %>%
      group_by(pregnancy_status) %>%
      summarise('Number of people visited in V5 (target: ?)' = n()) %>%
      arrange(pregnancy_status) %>%
      rename('PFU status' = pregnancy_status) %>%
      add_row('PFU status' = 'total people visited', 
              'Number of people visited in V5 (target: ?)' = sum(.$'Number of people visited in V5 (target: ?)')) %>%
      mutate('Percent complete' = (as.numeric(`Number of people visited in V5 (target: ?)`)) / as.numeric(nrow(pfu_v5)) * 100) %>%
      mutate('Percent complete' = round(`Percent complete`, 2)) %>%
      mutate('Percent complete' = paste0(`Percent complete`, '%'))
  
  
## V6 ########################
  pfu_v6 <- pfu %>%
    filter(visit == 'V6') 

  # change Status from logical to character
  pfu_v6$Status <- as.character(pfu_v6$Status)

  pfu_totals_v6 <- pfu_v6 %>%
      group_by(pregnancy_status) %>%
      summarise('Number of people visited in V6 (target: ?)' = n()) %>%
      arrange(pregnancy_status) %>%
      rename('PFU status' = pregnancy_status) %>%
      add_row('PFU status' = 'total people visited', 
              'Number of people visited in V6 (target: ?)' = sum(.$'Number of people visited in V6 (target: ?)')) %>%
      mutate('Percent complete' = (as.numeric(`Number of people visited in V6 (target: ?)`)) / as.numeric(nrow(pfu_v6)) * 100) %>%
      mutate('Percent complete' = round(`Percent complete`, 2)) %>%
      mutate('Percent complete' = paste0(`Percent complete`, '%'))
  
  
## V7 ########################
  pfu_v7 <- pfu %>%
    filter(visit == 'V7') 

  # change Status from logical to character
  pfu_v7$Status <- as.character(pfu_v7$Status)

  pfu_totals_v7 <- pfu_v7 %>%
      group_by(pregnancy_status) %>%
      summarise('Number of people visited in V7 (target: ?)' = n()) %>%
      arrange(pregnancy_status) %>%
      rename('PFU status' = pregnancy_status) %>%
      add_row('PFU status' = 'total people visited', 
              'Number of people visited in V7 (target: ?)' = sum(.$'Number of people visited in V7 (target: ?)')) %>%
      mutate('Percent complete' = (as.numeric(`Number of people visited in V7 (target: ?)`)) / as.numeric(nrow(pfu_v7)) * 100) %>%
      mutate('Percent complete' = round(`Percent complete`, 2)) %>%
      mutate('Percent complete' = paste0(`Percent complete`, '%'))
```

```{r data creation}
# create the merged v0 data
  v0dem <- left_join(v0_dem_repeat, v0_demography, by=c('PARENT_KEY' = 'KEY'))  %>%
    select(extid, dob, sex, todays_date) %>%
    rename(dob_v0 = dob,
           todays_date_v0 = todays_date,
           sex_v0 = sex)

# assign the reasons for eos and in
pfu_reason <- pfu %>%
  mutate(pregnancy_status_reason = case_when(pregnancy_status == 'in' ~ 'in',
                            ltfu_eos == '1' |
                              fourth_absence_eos == '1' ~ 'absent 4 times in a row: ltfu',
                            person_died_eos == '1' ~ 'died',
                            person_migrated_eos == '1' ~ 'migrated',
                            not_continue_eos == '1' ~ 'not wish to continue',
                            #still_preg_no_eos == '1' ~ 'no longer pregnant',
                            still_preg_no_eos == '1' & 
                              still_preg_no_reason == 'Baby was born alive' ~ 'no longer pregnant - baby born alive',
                            still_preg_no_eos == '1' &
                              still_preg_no_reason == 'Miscarriage' ~ 'no longer pregnant - miscarriage',
                            still_preg_no_eos == '1' &
                              still_preg_no_reason == 'Abortion (self-induced)' ~ 'no longer pregnant - abortion (self-induced)',
                            still_preg_no_eos == '1' &
                              still_preg_no_reason == 'Baby was born dead' ~ 'no longer pregnant - baby was born dead',
                            still_preg_no_eos == '1' &
                              still_preg_no_reason == 'pna' ~ 'no longer pregnant - prefer not to answer')) %>%
  rename(dob_pregnancy = dob_string,
         sex_pregnancy = sex,
         todays_date_pregnancy = todays_date)

# create the dataset that will be used for this script
  # this will exclude the people who were manually removed
  data <- left_join(v0dem, pfu_reason, by = c('extid')) # add manual changes with filter function here 
  
# create the dataset for the extid explorer
  data_investigation <- data %>%
    filter(!is.na(visit)) %>% # removes extids not in Efficacy
    select(visit, extid, pregnancy_status, pregnancy_status_reason, sex_v0, sex_pregnancy, dob_v0, dob_pregnancy, todays_date_v0, todays_date_pregnancy)

```

```{r eos_reason}
# create a table of the reasons a woman is eos

## V2 ####################

  pfu_eos_v2 <- data %>%
    filter(visit == 'V2',
           pregnancy_status == 'eos')

  eos_reasons_v2 <- pfu_eos_v2 %>%
      group_by(pregnancy_status_reason) %>%
      summarise('Number of eos people' = n()) %>%
      arrange(pregnancy_status_reason) %>%
      rename('Reason for eos' = pregnancy_status_reason) %>%
      add_row('Reason for eos' = 'total visited', 'Number of eos people' = sum(.$'Number of eos people')) %>%
      mutate('Percent complete' = (as.numeric(`Number of eos people`)) / as.numeric(nrow(pfu_eos_v2)) * 100) %>%
      mutate('Percent complete' = round(`Percent complete`, 2)) %>%
      mutate('Percent complete' = paste0(`Percent complete`, '%')) # Replace zero values with NA
  
  
## V3 ####################

  pfu_eos_v3 <- data %>%
    filter(visit == 'V3',
           pregnancy_status == 'eos')

  eos_reasons_v3 <- pfu_eos_v3 %>%
      group_by(pregnancy_status_reason) %>%
      summarise('Number of eos people' = n()) %>%
      arrange(pregnancy_status_reason) %>%
      rename('Reason for eos' = pregnancy_status_reason) %>%
      add_row('Reason for eos' = 'total visited', 'Number of eos people' = sum(.$'Number of eos people')) %>%
      mutate('Percent complete' = (as.numeric(`Number of eos people`)) / as.numeric(nrow(pfu_eos_v3)) * 100) %>%
      mutate('Percent complete' = round(`Percent complete`, 2)) %>%
      mutate('Percent complete' = paste0(`Percent complete`, '%')) # Replace zero values with NA
  
  
## V4 ####################

  pfu_eos_v4 <- data %>%
    filter(visit == 'V4',
           pregnancy_status == 'eos')

  eos_reasons_v4 <- pfu_eos_v4 %>%
      group_by(pregnancy_status_reason) %>%
      summarise('Number of eos people' = n()) %>%
      arrange(pregnancy_status_reason) %>%
      rename('Reason for eos' = pregnancy_status_reason) %>%
      add_row('Reason for eos' = 'total visited', 'Number of eos people' = sum(.$'Number of eos people')) %>%
      mutate('Percent complete' = (as.numeric(`Number of eos people`)) / as.numeric(nrow(pfu_eos_v4)) * 100) %>%
      mutate('Percent complete' = round(`Percent complete`, 2)) %>%
      mutate('Percent complete' = paste0(`Percent complete`, '%')) # Replace zero values with NA
  
  
## V5 ####################

  pfu_eos_v5 <- data %>%
    filter(visit == 'V5',
           pregnancy_status == 'eos')

  eos_reasons_v5 <- pfu_eos_v5 %>%
      group_by(pregnancy_status_reason) %>%
      summarise('Number of eos people' = n()) %>%
      arrange(pregnancy_status_reason) %>%
      rename('Reason for eos' = pregnancy_status_reason) %>%
      add_row('Reason for eos' = 'total visited', 'Number of eos people' = sum(.$'Number of eos people')) %>%
      mutate('Percent complete' = (as.numeric(`Number of eos people`)) / as.numeric(nrow(pfu_eos_v5)) * 100) %>%
      mutate('Percent complete' = round(`Percent complete`, 2)) %>%
      mutate('Percent complete' = paste0(`Percent complete`, '%')) # Replace zero values with NA
  
  
## V6 ####################

  pfu_eos_v6 <- data %>%
    filter(visit == 'V6',
           pregnancy_status == 'eos')

  eos_reasons_v6 <- pfu_eos_v6 %>%
      group_by(pregnancy_status_reason) %>%
      summarise('Number of eos people' = n()) %>%
      arrange(pregnancy_status_reason) %>%
      rename('Reason for eos' = pregnancy_status_reason) %>%
      add_row('Reason for eos' = 'total visited', 'Number of eos people' = sum(.$'Number of eos people')) %>%
      mutate('Percent complete' = (as.numeric(`Number of eos people`)) / as.numeric(nrow(pfu_eos_v6)) * 100) %>%
      mutate('Percent complete' = round(`Percent complete`, 2)) %>%
      mutate('Percent complete' = paste0(`Percent complete`, '%')) # Replace zero values with NA
  
  
## V7 ####################

  pfu_eos_v7 <- data %>%
    filter(visit == 'V7',
           pregnancy_status == 'eos')

  eos_reasons_v7 <- pfu_eos_v7 %>%
      group_by(pregnancy_status_reason) %>%
      summarise('Number of eos people' = n()) %>%
      arrange(pregnancy_status_reason) %>%
      rename('Reason for eos' = pregnancy_status_reason) %>%
      add_row('Reason for eos' = 'total visited', 'Number of eos people' = sum(.$'Number of eos people')) %>%
      mutate('Percent complete' = (as.numeric(`Number of eos people`)) / as.numeric(nrow(pfu_eos_v7)) * 100) %>%
      mutate('Percent complete' = round(`Percent complete`, 2)) %>%
      mutate('Percent complete' = paste0(`Percent complete`, '%')) # Replace zero values with NA
  
```

## PFU targets
```{r target_show}
reactable(target_table, columns = list(), pagination = FALSE)
```

## V3 Numbers
```{r v3_table_status}
reactable(pfu_totals_v3, columns = list(
  `Percent complete` = colDef(align = "right")
))

# make a note of the real total number of people visited without repeats
if (any(duplicated(pfu_totals_v3$extid))) {
  cat("Note: Excluding the duplicates, the real total number of people visited is", length(unique(pfu_totals_v2$extid)), "\n.")
} else {
  cat("Note: There are no duplicates based on extid in the data.")
}
```

### eos
```{r v3_table_eos_reason}
reactable(eos_reasons_v3, columns = list(
  `Percent complete` = colDef(align = 'right')
), pagination = FALSE) #pagination makes the entire table show on one page

# write which reasons do not appear in the table
# Specify the names you want to check for
names_to_check <- c('died',
                    'migrated',
                    'not wish to continue',
                    'no longer pregnant - baby born alive',
                    'no longer pregnant - miscarriage',
                    'no longer pregnant - abortion (self-induced)',
                    'no longer pregnant - baby was born dead',
                    'no longer pregnant - prefer not to answer')

# Initialize a vector to store names not found
not_found_names <- character(0)

# Check each name
for (name in names_to_check) {
  if (!name %in% eos_reasons_v3$reason) {
    not_found_names <- c(not_found_names, name)
  }
}

# Generate a message based on the results (only if names are not found)
if (length(not_found_names) > 0) {
  cat("The following reasons are not shown: ", paste0(not_found_names, collapse = " / "))
}
```

## V2 Numbers
```{r v2_table_status}
reactable(pfu_totals_v2, columns = list(
  `Percent complete` = colDef(align = "right")
))

# make a note of the real total number of people visited without repeats
if (any(duplicated(pfu_totals_v2$extid))) {
  cat("Note: Excluding the duplicates, the real total number of people visited is", length(unique(pfu_totals_v2$extid)), "\n.")
} else {
  cat("Note: There are no duplicates based on extid in the data.")
}
```

### eos
```{r v2_table_eos_reason}
reactable(eos_reasons_v2, columns = list(
  `Percent complete` = colDef(align = 'right')
), pagination = FALSE) #pagination makes the entire table show on one page

# write which reasons do not appear in the table
# Specify the names you want to check for
names_to_check <- c('died',
                    'migrated',
                    'not wish to continue',
                    'no longer pregnant - baby born alive',
                    'no longer pregnant - miscarriage',
                    'no longer pregnant - abortion (self-induced)',
                    'no longer pregnant - baby was born dead',
                    'no longer pregnant - prefer not to answer')

# Initialize a vector to store names not found
not_found_names <- character(0)

# Check each name
for (name in names_to_check) {
  if (!name %in% eos_reasons_v2$reason) {
    not_found_names <- c(not_found_names, name)
  }
}

# Generate a message based on the results (only if names are not found)
if (length(not_found_names) > 0) {
  cat("The following reasons are not shown: ", paste0(not_found_names, collapse = " / "))
}
```

## PFU extid explorer
```{r pfu-explorer}
element_id <- 'extid-explorerer'

data_readable <- reactable(data_investigation, columns = list(), 
                                              highlight = TRUE,
                                              resizable = TRUE,
                                              bordered = TRUE,
                                              striped = TRUE,
                                              filterable=TRUE,
                                              elementId = element_id
                                              )

wrap_download(
  data_readable, 
  element_id,
  'pfu_extid_explorer.csv')
```