---
title: "Safety Status Report"
output: 
  html_document:
    toc: true
    theme: cerulean
date: '`r Sys.time()`'
---

Notes:

- Report is refreshed hourly 9-5pm EAT, once 12AM EAT
- Please reach out to nikamgorski@gmail.com for bug reports


```{r, echo=FALSE, message=FALSE}
knitr::opts_chunk$set(
  comment = '', 
  echo = FALSE,
  message = FALSE,
  cache=FALSE,
  warning=FALSE
)
```

```{r setup, include=FALSE}
### PURPOSE:
# This code aims to determine who is out, refusal, in, and eos after safety. This information comes from Safety, Safetynew, and Absence1stattempt. Then for each status (except of in), split each status into the "reason" or the "how" they got to that status.
# load required libraries
library(dplyr)
library(reactable)
library(data.table)
library(cloudbrewr)
library(fontawesome)
library(shiny)
library(ggplot2)
library(tidyr)

ENV_PIPELINE_STAGE <- Sys.getenv("PIPELINE_STAGE")
DATA_STAGING_BUCKET_NAME <- 'databrew.org'
DATA_LAKE_BUCKET_NAME <- 'bohemia-lake-db'
PROJECT_SOURCE <- 'kwale'
SE_FOLDER_TARGET <- glue::glue('{PROJECT_SOURCE}/clean-form')

pad_hhid <- function(data){
  if('hhid' %in% names(data)){
    data %>%
      dplyr::mutate(hhid = stringr::str_pad(hhid, 5, pad = "0"))
  }else{
    data
  }
}


tryCatch({
  logger::log_info('Attempt AWS login')
  # login to AWS - this will be bypassed if executed in CI/CD environment
  cloudbrewr::aws_login(
    role_name = 'cloudbrewr-aws-role',
    profile_name =  'cloudbrewr-aws-role',
    pipeline_stage = ENV_PIPELINE_STAGE)

}, error = function(e){
  logger::log_error('AWS Login Failed')
  stop(e$message)
})


# load in the data
absence1stattempt <- cloudbrewr::aws_s3_get_table(
  bucket = DATA_STAGING_BUCKET_NAME,
  key = glue::glue('{PROJECT_SOURCE}/sanitized-form/absences1stattempt/absences1stattempt.csv')) %>%
  pad_hhid()

v0_demography <- cloudbrewr::aws_s3_get_table(
  bucket = DATA_STAGING_BUCKET_NAME,
  key = glue::glue('{PROJECT_SOURCE}/sanitized-form/v0demography/v0demography-repeat_individual.csv')) %>%
  pad_hhid()

safety <- cloudbrewr::aws_s3_get_table(
  bucket = DATA_STAGING_BUCKET_NAME,
  key = glue::glue('{PROJECT_SOURCE}/sanitized-form/safety/safety.csv')) %>%
  pad_hhid()

safetynew <- cloudbrewr::aws_s3_get_table(
  bucket =DATA_STAGING_BUCKET_NAME,
  key = glue::glue('{PROJECT_SOURCE}/sanitized-form/safetynew/safetynew.csv')) %>%
  pad_hhid()

safety_repeat_individual <- cloudbrewr::aws_s3_get_table(
  bucket = DATA_STAGING_BUCKET_NAME,
  key = glue::glue('{PROJECT_SOURCE}/sanitized-form/safety/safety-repeat_individual.csv')) %>%
  pad_hhid()

safetynew_repeat_individual <- cloudbrewr::aws_s3_get_table(
  bucket =DATA_STAGING_BUCKET_NAME,
  key = glue::glue('{PROJECT_SOURCE}/sanitized-form/safetynew/safetynew-repeat_individual.csv')) %>%
  pad_hhid()

# this is a function to create a download csv button
wrap_download <- function(reactable_obj, element_id, output_filename){
  onclick_command <- glue::glue(
    "Reactable.downloadDataCSV('{element_id}', '{output_filename}')")
  htmltools::browsable(
    tagList(
      tags$button(
        tagList(fontawesome::fa("download"), "Download as CSV"),
        onclick = onclick_command),
      reactable_obj
    ))
}
```

```{r targets}
# these numbers are determined from the safety target csvs sent by Joe
target_table <- rbind(data.frame(
  Visit = c('Safety V1', 'Safety V2'),
  'Person target' = c('28478', '26484'),
  'HH target' = c('5847', '5492')))

# only take the necessary columns (extid and safety_status) from the datasets
clean_safety_repeat <- safety_repeat_individual %>%
  select(PARENT_KEY, extid, safety_status, sex)
clean_safetynew_repeat <- safetynew_repeat_individual %>%
  select(PARENT_KEY, extid, safety_status, sex) %>%
  rename(safetynew_status = safety_status,
         sex_safetynew = sex)
clean_safety <- safety %>%
  select(KEY, visit, cluster, hhid, todays_date)
clean_safetynew <- safetynew %>%
  select(KEY, visit, cluster, hhid, todays_date)

# join safety and safety repeat and do the same for safetynew
joined_safety <- left_join(clean_safety_repeat, clean_safety, by=c('PARENT_KEY' = 'KEY'))
joined_safetynew <- left_join(clean_safetynew_repeat, clean_safetynew, by=c('PARENT_KEY' = 'KEY'))

# join these two new dataframes
total_safety <- bind_rows(joined_safety, joined_safetynew)

# identify how many households were visited in V1 and V2
total_safety_v1 <- total_safety %>%
  filter(visit == 'V1') %>%
  group_by(hhid) %>%
  summarise(count = n()) %>%
  mutate(
    Visit = 'Safety V1',
    `HH visited` = n() # Replace nrow(hhid) with n() to count the households visited
  ) %>%
  select(Visit, `HH visited`) %>% # Selecting only the required columns %>%
  distinct(Visit, .keep_all = TRUE)

total_safety_v2 <- total_safety %>%
  filter(visit == 'V2') %>%
  group_by(hhid) %>%
  summarise(count = n()) %>%
  mutate(
    Visit = 'Safety V2',
    `HH visited` = n() # Replace nrow(hhid) with n() to count the households visited
  ) %>%
  select(Visit, `HH visited`) %>% # Selecting only the required columns %>%
  distinct(Visit, .keep_all = TRUE)

total_safety_v1_2 <- rbind(total_safety_v1, total_safety_v2)

# join the number of households visited and targets
target_table <- left_join(target_table, total_safety_v1_2, by=('Visit'))
```

```{r totals}
## this will create the table of how many people are in, out, refusal, or eos
## it is broken up into each visit number

### V1

# make the safetynew_status and safety_status into one column and the sexes
total_safety <- total_safety %>%
  mutate(safetystatus = coalesce(safety_status, safetynew_status),
                                 sex = coalesce(sex, sex_safetynew)) %>% 
  select(extid, safetystatus, cluster, sex, todays_date, visit) %>%
  filter(safetystatus != 'UNDEFINED') # we find an UNDEFINED from someone most likely submitting a form without filling it out so we will remove NA from extid 

# since this is only a table for V1 we will only keep V1 people from total_safety
total_safety_v1 <- total_safety %>%
  filter(visit == 'V1')

# create a summary table of safety_status counts
total_safety_status_v1 <- total_safety_v1 %>%
  group_by(safetystatus) %>%
  summarise('Number of people visited in V1 (target: 28,479)' = n()) %>%
  arrange(safetystatus) %>%
  rename('Safety status' = safetystatus) %>%
  add_row('Safety status' = 'total people visited', 'Number of people visited in V1 (target: 28,479)' = sum(.$'Number of people visited in V1 (target: 28,479)')) %>%
  mutate('Percent complete' = (as.numeric(`Number of people visited in V1 (target: 28,479)`)) / as.numeric(nrow(total_safety_v1)) * 100) %>%
  mutate('Percent complete' = round(`Percent complete`, 2)) %>%
  mutate('Percent complete' = paste0(`Percent complete`, '%'))


## V2
total_safety_v2 <- total_safety %>%
  filter(visit == 'V2')

total_safety_status_v2 <- total_safety_v2 %>%
  group_by(safetystatus) %>%
  summarise('Number of people visited in V2 (target: 26,485)' = n()) %>%
  arrange(safetystatus) %>%
  rename('Safety status' = safetystatus) %>%
  add_row('Safety status' = 'total people visited', 'Number of people visited in V2 (target: 26,485)' = sum(.$'Number of people visited in V2 (target: 26,485)')) %>%
  mutate('Percent complete' = (as.numeric(`Number of people visited in V2 (target: 26,485)`)) / as.numeric(nrow(total_safety_v2)) * 100) %>%
  mutate('Percent complete' = round(`Percent complete`, 2)) %>%
  mutate('Percent complete' = paste0(`Percent complete`, '%'))
```

```{r in}
## this will create a table of how many people are in as enrolment and in as follow up in Safety V2
# first create a dataset with the in safety status people from SafetyV2 and then joining Safety V1 and V2 (total_safety_v1 and total_safety_v2)
safety_v2 <- total_safety_v2 %>%
  rename(v2_safetystatus = safetystatus) %>%
  select(extid, v2_safetystatus) # get the v2 'in' people

safety_v2 <- left_join(safety_v2, total_safety_v1, by=c('extid')) %>%
  select(extid, safetystatus, v2_safetystatus) %>%
  rename(v1_safetystatus = safetystatus) # join the v2 'in' people with their v1 statuses

#safe_in <- left_join(safety_in, safety_repeat_individual, by=c("extid")) 

#safe_in <- safe_in %>% select(extid, v1_safetystatus, v2_safetystatus, continue_participation, obvious_screening) # add the continue_participation and obvious_screening columns for double checking purposes below
  
# create a column that says whether the safety people are follow up or enrolment. This will be determined in two ways:
# A. classify as follow up if they were 'in' in V1 and 'in' in V2 AND classify as enrolment if they were 'out' in V1 and 'in' in V2
safety_v2$visit_type[safety_v2$v1_safetystatus == 'in'] <- 'follow up'
safety_v2$visit_type[safety_v2$v1_safetystatus == 'out' | is.na(safety_v2$v1_safetystatus)] <- 'enrolment'

safety_in <- safety_v2 %>%
  filter(v2_safetystatus == 'in')

# B. classify as follow up if they answered continue_participation AND classify as enrolment if they answered obvious_screening
# we are doing this two different ways to make sure we catch any errors
#safe_in$visit_type_b[safe_in$obvious_screening == 'NA'] <- "follow up"
#safe_in$visit_type_b[safe_in$continue_participation == 'NA'] <- "enrolment"

# create a table that shows how many people are follow up and enrolment in V2
# make a table of reasons people are eos
in_type_v2 <- safety_in %>%
  group_by(visit_type) %>%
  summarise('Number of in people' = n()) %>%
  arrange(visit_type) %>%
  rename('Visit type' = visit_type) %>%
  add_row('Visit type' = 'total in', 'Number of in people' = sum(.$'Number of in people')) %>%
  mutate('Percent' = (as.numeric(`Number of in people`)) / as.numeric(nrow(safety_in)) * 100) %>%
  mutate('Percent' = round(`Percent`, 2)) %>%
  mutate('Percent' = paste0(`Percent`, '%')) # Replace zero values with NA

```

```{r eos}
## this will create a table of how many people are eos and why they are eos
# first let's determine the reason someone is eos in the safety repeat individual form 
safety_eos <- safety_repeat_individual %>%
  select(PARENT_KEY, extid, safety_status, not_agree_safety_procedures_eos, safety_inclusion_eos, non_resident_eos, weight_eos, study_drug_eos, concom_meds_eos, severe_illness_eos, baby_not_week_old_eos, pregnant_eos, pregnancy_section_eos, other_trials_eos, loa_loa_eos, sum_night_hospital_eos, pregnancy_section_eos_short, preg_test_refuse_eos_short, preg_test_pos_eos_short, preg_test_2_eos_short, short_safety_inclusion_eos, weight_eos_short, concom_meds_eos_short, severe_illness_eos_short, refuse_drug_eos, not_take_drug_reason, refuse_drug_eos_2, not_take_drug_reason_2, person_died_eos, starting_safety_status, person_migrated, not_continue_eos, starting_safety_status) %>%
  mutate(type = 'safety') %>%
  filter(safety_status == 'eos')# to identify where the person came from later on

# need to filter by visit from clean_safety
safety_eos_v1 <- left_join(safety_eos, clean_safety, by=c('PARENT_KEY'='KEY')) %>%
  filter(visit == 'V1')

# conditions for not_agree_to_safety_procedures
safety_eos_v1$reason[safety_eos_v1$not_agree_safety_procedures_eos == 1] <- 'not agree to safety procedures'

# conditions for safety_inclusion_eos
safety_eos_v1$reason[safety_eos_v1$non_resident_eos == 1] <- 'not resident'
safety_eos_v1$reason[safety_eos_v1$weight_eos == 1] <- 'under weight'
safety_eos_v1$reason[safety_eos_v1$study_drug_eos == 1] <- 'study drug'
safety_eos_v1$reason[safety_eos_v1$concom_meds_eos == 1] <- 'concom meds'
safety_eos_v1$reason[safety_eos_v1$severe_illness_eos == 1] <- 'severe illness'
safety_eos_v1$reason[safety_eos_v1$baby_not_week_old_eos == 1] <- 'baby under 1 week'
safety_eos_v1$reason[safety_eos_v1$pregnant_eos == 1] <- 'pregnant'
safety_eos_v1$reason[safety_eos_v1$pregnancy_section_eos == 1] <- 'pregnant'
safety_eos_v1$reason[safety_eos_v1$other_trials_eos == 1] <- 'other trials'
safety_eos_v1$reason[safety_eos_v1$loa_loa_eos == 1] <- 'visited loa loa'

# conditions for sum_night_hospital_eos
safety_eos_v1$reason[safety_eos_v1$sum_night_hospital_eos >= 1] <- 'spent night at the hospital'

# conditions for pregnancy_section_eos_short
safety_eos_v1$reason[safety_eos_v1$preg_test_refuse_eos_short == 1] <- 'pregnancy test refusal'
safety_eos_v1$reason[safety_eos_v1$preg_test_pos_eos_short == 1 |
                       safety_eos_v1$preg_test_2_eos_short == 1] <- 'pregnant'

# conditions for short_safety_inclusion_eos
safety_eos_v1$reason[safety_eos_v1$pregnancy_section_eos_short == 1] <- 'pregnant'
safety_eos_v1$reason[safety_eos_v1$weight_eos_short == 1] <- 'under weight'
safety_eos_v1$reason[safety_eos_v1$concom_meds_eos_short == 1] <- 'concom meds'
safety_eos_v1$reason[safety_eos_v1$severe_illness_eos_short == 1] <- 'severe illness'

# conditions for refuse_drug_eos
safety_eos_v1$reason[safety_eos_v1$refuse_drug_eos == 1 |
                       safety_eos_v1$refuse_drug_eos_2 == 1] <- 'participant withdrew informed consent'

# next let's determine the reason someone is eos in the safetynew repeat individual data
safetynew_eos <- safetynew_repeat_individual %>%
  select(PARENT_KEY, extid, safety_status, not_agree_safety_procedures_eos, safety_inclusion_eos, non_resident_eos, weight_eos, study_drug_eos, concom_meds_eos, severe_illness_eos, baby_not_week_old_eos, pregnant_eos, pregnancy_section_eos, other_trials_eos, loa_loa_eos, refuse_drug_eos, not_take_drug_reason, refuse_drug_eos_2, not_take_drug_reason_2) %>%
  mutate(type = 'safety new') %>%
  filter(safety_status == 'eos')

# get the visit number from clean_safetynew
safetynew_eos_v1 <- left_join(safetynew_eos, clean_safetynew, by=c('PARENT_KEY' = 'KEY')) %>%
  filter(visit == 'V1')

# conditions for not_agree_to_safety_procedures
safetynew_eos_v1$reason[safetynew_eos_v1$not_agree_safety_procedures_eos == 1] <- 'not agree to safety procedures'

# conditions for safety_inclusion_eos
safetynew_eos_v1$reason[safetynew_eos_v1$non_resident_eos == 1] <- 'not resident'
safetynew_eos_v1$reason[safetynew_eos_v1$weight_eos == 1] <- 'under weight'
safetynew_eos_v1$reason[safetynew_eos_v1$study_drug_eos == 1] <- 'study drug'
safetynew_eos_v1$reason[safetynew_eos_v1$concom_meds_eos == 1] <- 'concom meds'
safetynew_eos_v1$reason[safetynew_eos_v1$severe_illness_eos == 1] <- 'severe illness'
safetynew_eos_v1$reason[safetynew_eos_v1$baby_not_week_old_eos == 1] <- 'baby under 1 week'
safetynew_eos_v1$reason[safetynew_eos_v1$pregnant_eos == 1 | 
                          safetynew_eos_v1$pregnancy_section_eos == 1] <- 'pregnant'
safetynew_eos_v1$reason[safetynew_eos_v1$other_trials_eos == 1] <- 'other trials'
safetynew_eos_v1$reason[safetynew_eos_v1$loa_loa_eos == 1] <- 'visited loa loa'

# conditions for refuse_drug_eos
safetynew_eos_v1$reason[safetynew_eos_v1$refuse_drug_eos == 1 |
                          safetynew_eos_v1$refuse_drug_eos_2 == 1] <- 'participant withdrew informed consent'

# join safetynew_eos and safety_eos by extid, safety status, and reason
total_safe_eos_v1 <- bind_rows(safety_eos_v1, safetynew_eos_v1)

# make a table of reasons people are eos
eos_reasons_v1 <- total_safe_eos_v1 %>%
  group_by(reason) %>%
  summarise('Number of eos people' = n()) %>%
  arrange(reason) %>%
  rename('Reason for eos' = reason) %>%
  add_row('Reason for eos' = 'total visited', 'Number of eos people' = sum(.$'Number of eos people')) %>%
  mutate('Percent complete' = (as.numeric(`Number of eos people`)) / as.numeric(nrow(total_safe_eos_v1)) * 100) %>%
  mutate('Percent complete' = round(`Percent complete`, 2)) %>%
  mutate('Percent complete' = paste0(`Percent complete`, '%')) # Replace zero values with NA


## V2######################################
safety_eos_v2 <- left_join(safety_eos, clean_safety, by=c('PARENT_KEY'='KEY')) %>%
  filter(visit == 'V2')

# create a reason column
safety_eos_v2$reason[safety_eos_v2$not_continue_eos == '1'] <- 'not wish to continue'
safety_eos_v2$reason[safety_eos_v2$not_agree_safety_procedures_eos == 1] <- 'not agree to safety procedures'
safety_eos_v2$reason[safety_eos_v2$non_resident_eos == 1] <- 'not resident'
safety_eos_v2$reason[safety_eos_v2$weight_eos == 1 |
                       safety_eos_v2$weight_eos_short == 1] <- 'under weight'
safety_eos_v2$reason[safety_eos_v2$study_drug_eos == 1] <- 'study drug'
safety_eos_v2$reason[safety_eos_v2$concom_meds_eos == 1 |
                       safety_eos_v2$concom_meds_eos_short == 1] <- 'concom meds'
safety_eos_v2$reason[safety_eos_v2$severe_illness_eos == 1 |
                       safety_eos_v2$severe_illness_eos_short == 1] <- 'severe illness'
safety_eos_v2$reason[safety_eos_v2$baby_not_week_old_eos == 1] <- 'baby under 1 week'
safety_eos_v2$reason[safety_eos_v2$pregnant_eos == 1 |
                       safety_eos_v2$pregnancy_section_eos == 1 |
                       safety_eos_v2$pregnancy_section_eos_short == 1 |
                       safety_eos_v2$preg_test_pos_eos_short == 1 |
                       safety_eos_v2$preg_test_2_eos_short == 1] <- 'pregnant'
safety_eos_v2$reason[safety_eos_v2$other_trials_eos == 1] <- 'other trials'
safety_eos_v2$reason[safety_eos_v2$loa_loa_eos == 1] <- 'visited loa loa'
safety_eos_v2$reason[safety_eos_v2$sum_night_hospital_eos >= 1] <- 'spent night at the hospital'
safety_eos_v2$reason[safety_eos_v2$preg_test_refuse_eos_short == 1] <- 'pregnancy test refusal'
safety_eos_v2$reason[safety_eos_v2$refuse_drug_eos == 1 |
                       safety_eos_v2$refuse_drug_eos_2 == 1] <- 'participant withdrew informed consent'
safety_eos_v2$reason[safety_eos_v2$person_died_eos == 1] <- 'died'
safety_eos_v2$reason[safety_eos_v2$person_migrated == 1 &
                       safety_eos_v2$starting_safety_status == 'in'] <- 'migrated'
safety_eos_v2$reason[safety_eos_v2$starting_safety_status == 'eos'] <- 'eos in V1'


# do the same for safetynew V2
safetynew_eos_v2 <- left_join(safetynew_eos, clean_safetynew, by=c('PARENT_KEY' = 'KEY')) %>%
  filter(visit == 'V2')

# create a reason column
safetynew_eos_v2$reason[safetynew_eos_v2$not_agree_safety_procedures_eos == 1] <- 'not agree to safety procedures'
safetynew_eos_v2$reason[safetynew_eos_v2$non_resident_eos == 1] <- 'not resident'
safetynew_eos_v2$reason[safetynew_eos_v2$weight_eos == 1] <- 'under weight'
safetynew_eos_v2$reason[safetynew_eos_v2$study_drug_eos == 1] <- 'study drug'
safetynew_eos_v2$reason[safetynew_eos_v2$concom_meds_eos == 1] <- 'concom meds'
safetynew_eos_v2$reason[safetynew_eos_v2$severe_illness_eos == 1] <- 'severe illness'
safetynew_eos_v2$reason[safetynew_eos_v2$baby_not_week_old_eos == 1] <- 'baby under 1 week'
safetynew_eos_v2$reason[safetynew_eos_v2$pregnant_eos == 1 |
                          safetynew_eos_v2$pregnancy_section_eos == 1] <- 'pregnant'
safetynew_eos_v2$reason[safetynew_eos_v2$other_trials_eos == 1] <- 'other trials'
safetynew_eos_v2$reason[safetynew_eos_v2$loa_loa_eos == 1] <- 'visited loa loa'
safetynew_eos_v2$reason[safetynew_eos_v2$refuse_drug_eos == 1 |
                          safetynew_eos_v2$refuse_drug_eos_2 == 1] <- 'participant withdrew informed consent'

# join safetynew_eos and safety_eos by extid, safety status, and reason
total_safe_eos_v2 <- bind_rows(safety_eos_v2, safetynew_eos_v2)

# need the visit_type variable from safety_v2 to make two different eos tables (enrolment vs. follow up)
total_safe_eos_v2 <- left_join(total_safe_eos_v2, safety_v2, by=c('extid'))

total_safe_eos_enrolment_v2 <- total_safe_eos_v2 %>%
  filter(visit_type == 'enrolment')
total_safe_eos_followup_v2 <- total_safe_eos_v2 %>%
  filter(visit_type == 'follow up')

# make a table of both enrolment and followup together since they will be split up later
eos_reasons_v2 <- total_safe_eos_v2 %>%
  group_by(reason) %>%
  filter(reason == 'eos in V1') %>%
  summarise('Number of eos people' = n()) %>%
  rename('Reason for eos' = reason) %>%
  mutate('Percent of eos' = (as.numeric(`Number of eos people`)) / as.numeric(nrow(total_safe_eos_v2)) * 100) %>%
  mutate('Percent of eos' = round(`Percent of eos`, 2)) %>%
  mutate('Percent of eos' = paste0(`Percent of eos`, '%')) # Replace zero values with NA

# make a table of enrolment people who are eos
eos_reasons_enrolment_v2 <- total_safe_eos_enrolment_v2 %>%
  group_by(reason) %>%
  summarise('Number of eos people' = n()) %>%
  arrange(reason) %>%
  rename('Reason for eos' = reason) %>%
  add_row('Reason for eos' = 'total visited', 'Number of eos people' = sum(.$'Number of eos people')) %>%
  mutate('Percent complete' = (as.numeric(`Number of eos people`)) / as.numeric(nrow(total_safe_eos_enrolment_v2)) * 100) %>%
  mutate('Percent complete' = round(`Percent complete`, 2)) %>%
  mutate('Percent complete' = paste0(`Percent complete`, '%')) # Replace zero values with NA

# make a table of reasons follow up people are eos #
eos_reasons_followup_v2 <- total_safe_eos_followup_v2 %>%
  group_by(reason) %>%
  summarise('Number of eos people' = n()) %>%
  arrange(reason) %>%
  rename('Reason for eos' = reason) %>%
  add_row('Reason for eos' = 'total visited', 'Number of eos people' = sum(.$'Number of eos people')) %>%
  mutate('Percent complete' = (as.numeric(`Number of eos people`)) / as.numeric(nrow(total_safe_eos_followup_v2)) * 100) %>%
  mutate('Percent complete' = round(`Percent complete`, 2)) %>%
  mutate('Percent complete' = paste0(`Percent complete`, '%')) # Replace zero values with NA
```

```{r v1_out}
## this will create a table of how many people are out and why they are out
# let's start with safety
safety_out <- safety_repeat_individual %>%
  select('PARENT_KEY', 'extid', 'safety_status', 'person_out_died', 'person_out_migrated', 'obvious_screening_status', 'obvious_screening', 'person_absent') %>%
  mutate(type = 'safety') %>%
  filter(safety_status == 'out')

# need to filter by visit from clean_safety
safety_out_v1 <- left_join(safety_out, clean_safety, by=c('PARENT_KEY'='KEY')) %>%
  filter(visit == 'V1')

safety_out_v1$reason[safety_out_v1$person_out_died == 1] <- 'died'
safety_out_v1$reason[safety_out_v1$person_out_migrated == 1] <- 'migrated'
safety_out_v1$reason[safety_out_v1$obvious_screening == 'ineligible'] <- 'Ineligible at obvious reasoning'
safety_out_v1$reason[safety_out_v1$obvious_screening == 'Pregnant'] <- 'pregnant'
safety_out_v1$reason[safety_out_v1$obvious_screening == 'Baby'] <- 'A baby that cannot walk yet'
safety_out_v1$reason[safety_out_v1$obvious_screening == 'Ill'] <- 'A person so ill that they cannot leave the bed'
safety_out_v1$reason[safety_out_v1$obvious_screening == 'Witness'] <- 'no witness'
safety_out_v1$reason[safety_out_v1$person_absent == '1'] <- 'absent'

# create a new df for safetynew for out individuals with the reason
safetynew_out <- safetynew_repeat_individual %>%
  select('PARENT_KEY', 'extid', 'safety_status', 'obvious_screening_status', 'obvious_screening', 'ind_witness_present') %>%
  mutate(type = 'safetynew') %>%
  filter(safety_status == 'out')

# need to filter by visit from clean_safety
safetynew_out_v1 <- left_join(safetynew_out, clean_safetynew, by=c('PARENT_KEY'='KEY')) %>%
  filter(visit == 'V1')

safetynew_out_v1$reason[safetynew_out_v1$obvious_screening == 'ineligible'] <- 'Ineligible at obvious reasoning'
safetynew_out_v1$reason[safetynew_out_v1$obvious_screening == 'Pregnant'] <- 'pregnant'
safetynew_out_v1$reason[safetynew_out_v1$obvious_screening == 'Baby'] <- 'A baby that cannot walk yet'
safetynew_out_v1$reason[safetynew_out_v1$obvious_screening == 'Ill'] <- 'A person so ill that they cannot leave the bed'
safetynew_out_v1$reason[safetynew_out_v1$obvious_screening == 'Witness' |
                          safetynew_out_v1$ind_witness_present == 'no'] <- 'no witness'

# merge the datasets to see why people are out
total_safe_out_v1 <- bind_rows(safety_out_v1, safetynew_out_v1)

# create the table
out_reasons_v1 <- total_safe_out_v1 %>%
  group_by(reason) %>%
  summarise('Number of out people' = n()) %>%
  arrange(reason) %>%
  rename(Reason = reason) %>%
  add_row(Reason = 'total number of people', 'Number of out people' = sum(.$'Number of out people')) %>%
  mutate('Percent complete' = (as.numeric(`Number of out people`)) / as.numeric(nrow(total_safe_out_v1)) * 100) %>%
  mutate('Percent complete' = round(`Percent complete`, 2)) %>%
  mutate('Percent complete' = paste0(`Percent complete`, '%'))


## V2
# need to filter by visit from clean_safety
safety_out_v2 <- left_join(safety_out, clean_safety, by=c('PARENT_KEY'='KEY')) %>%
  filter(visit == 'V2')

safety_out_v2$reason[safety_out_v2$person_out_died == 1] <- 'died'
safety_out_v2$reason[safety_out_v2$person_out_migrated == 1] <- 'migrated'
safety_out_v2$reason[safety_out_v2$obvious_screening == 'ineligible'] <- 'Ineligible at obvious reasoning'
safety_out_v2$reason[safety_out_v2$obvious_screening == 'Pregnant'] <- 'pregnant'
safety_out_v2$reason[safety_out_v2$obvious_screening == 'Baby'] <- 'A baby that cannot walk yet'
safety_out_v2$reason[safety_out_v2$obvious_screening == 'Ill'] <- 'A person so ill that they cannot leave the bed'
safety_out_v2$reason[safety_out_v2$obvious_screening == 'Witness'] <- 'no witness'
safety_out_v2$reason[safety_out_v2$person_absent == '1'] <- 'absent'

# need to filter by visit from clean_safety
safetynew_out_v2 <- left_join(safetynew_out, clean_safetynew, by=c('PARENT_KEY'='KEY')) %>%
  filter(visit == 'V2')

safetynew_out_v2$reason[safetynew_out_v2$obvious_screening == 'ineligible'] <- 'Ineligible at obvious reasoning'
safetynew_out_v2$reason[safetynew_out_v2$obvious_screening == 'Pregnant'] <- 'pregnant'
safetynew_out_v2$reason[safetynew_out_v2$obvious_screening == 'Baby'] <- 'A baby that cannot walk yet'
safetynew_out_v2$reason[safetynew_out_v2$obvious_screening == 'Ill'] <- 'A person so ill that they cannot leave the bed'
safetynew_out_v2$reason[safetynew_out_v2$obvious_screening == 'Witness' |
                          safetynew_out_v2$ind_witness_present == 'no'] <- 'no witness'

# merge the datasets to see why people are out
total_safe_out_v2 <- bind_rows(safety_out_v2, safetynew_out_v2)

# create the table
out_reasons_v2 <- total_safe_out_v2 %>%
  group_by(reason) %>%
  summarise('Number of out people' = n()) %>%
  arrange(reason) %>%
  rename(Reason = reason) %>%
  add_row(Reason = 'total number of people', 'Number of out people' = sum(.$'Number of out people')) %>%
  mutate('Percent complete' = (as.numeric(`Number of out people`)) / as.numeric(nrow(total_safe_out_v2)) * 100) %>%
  mutate('Percent complete' = round(`Percent complete`, 2)) %>%
  mutate('Percent complete' = paste0(`Percent complete`, '%'))

```

```{r refusal}
## this will create a table of how many people are refusal and why they are refusal
# let us start with safety
safety_refusal <- safety_repeat_individual %>%
  select('PARENT_KEY', 'extid', 'safety_status', 'obvious_screening_status', 'obvious_screening', 'ind_thumbprint_status', 'ind_sign_icf_status', 'minor_assent_status', starting_safety_status) %>%
  mutate(type = 'safety') %>%
  filter(safety_status == 'refusal')

# need to filter by visit from clean_safety
safety_refusal_v1 <- left_join(safety_refusal, clean_safety, by=c('PARENT_KEY'='KEY')) %>%
  filter(visit == 'V1')

safety_refusal_v1$reason[safety_refusal_v1$obvious_screening == 'Refusal'] <- 'a person who does not want to participate'
safety_refusal_v1$reason[safety_refusal_v1$obvious_screening == 'Pregnant'] <- 'pregnant'
safety_refusal_v1$reason[safety_refusal_v1$obvious_screening == 'Baby'] <- 'A baby that cannot walk yet'
safety_refusal_v1$reason[safety_refusal_v1$obvious_screening == 'Ill'] <- 'A person so ill that they cannot leave the bed'
safety_refusal_v1$reason[safety_refusal_v1$obvious_screening == 'Language'] <- 'does not speak English or Swahili'
safety_refusal_v1$reason[safety_refusal_v1$obvious_screening == 'Witness'] <- 'no witness'
safety_refusal_v1$reason[safety_refusal_v1$ind_thumbprint_status == 0] <- 'not consented or provided their thumbprint'
safety_refusal_v1$reason[safety_refusal_v1$ind_sign_icf_status == 0] <- 'not agree or sign informed consent'
safety_refusal_v1$reason[safety_refusal_v1$minor_assent_status == 0] <- 'minor not sign assent'

# next we will work with safety new
safetynew_refusal <- safetynew_repeat_individual %>%
  select('PARENT_KEY', 'extid', 'safety_status', 'obvious_screening_status', 'obvious_screening', 'ind_thumbprint_status', 'ind_sign_icf_status', 'minor_assent_status') %>%
  mutate(type = 'safetynew') %>%
  filter(safety_status == 'refusal')

# need to filter by visit from clean_safety
safetynew_refusal_v1 <- left_join(safetynew_refusal, clean_safetynew, by=c('PARENT_KEY'='KEY')) %>%
  filter(visit == 'V1')

safetynew_refusal_v1$reason[safetynew_refusal_v1$obvious_screening == 'Refusal'] <- 'a person who does not want to participate'
safetynew_refusal_v1$reason[safetynew_refusal_v1$obvious_screening == 'Pregnant'] <- 'pregnant'
safetynew_refusal_v1$reason[safetynew_refusal_v1$obvious_screening == 'Baby'] <- 'A baby that cannot walk yet'
safetynew_refusal_v1$reason[safetynew_refusal_v1$obvious_screening == 'Ill'] <- 'A person so ill that they cannot leave the bed'
safetynew_refusal_v1$reason[safetynew_refusal_v1$obvious_screening == 'Language'] <- 'does not speak English or Swahili'
safetynew_refusal_v1$reason[safetynew_refusal_v1$obvious_screening == 'Witness'] <- 'no witness'
safetynew_refusal_v1$reason[safetynew_refusal_v1$ind_thumbprint_status == 0] <- 'not consented or provided their thumbprint'
safetynew_refusal_v1$reason[safetynew_refusal_v1$ind_sign_icf_status == 0] <- 'not agree or sign informed consent'
safetynew_refusal_v1$reason[safetynew_refusal_v1$minor_assent_status == 0] <- 'minor not sign assent'

# combine both datasets to be able to make a table of refusal reasons
total_safe_refusal_v1 <- bind_rows(safety_refusal_v1, safetynew_refusal_v1)

# make the table
refusal_reasons_v1 <- total_safe_refusal_v1 %>%
  group_by(reason) %>%
  summarise('Number of refusal people' = n()) %>%
  arrange(reason) %>%
  rename(Reason = reason) %>%
  add_row(Reason = 'total number of people', 'Number of refusal people' = sum(.$'Number of refusal people')) %>%
  mutate('Percent complete' = (as.numeric(`Number of refusal people`)) / as.numeric(nrow(total_safe_refusal_v1)) * 100) %>%
  mutate('Percent complete' = round(`Percent complete`, 2)) %>%
  mutate('Percent complete' = paste0(`Percent complete`, '%'))


## V2
# need to filter by visit from clean_safety
safety_refusal_v2 <- left_join(safety_refusal, clean_safety, by=c('PARENT_KEY'='KEY')) %>%
  filter(visit == 'V2')

safety_refusal_v2$reason[safety_refusal_v2$starting_safety_status == 'refusal'] <- 'V1 refusal'
safety_refusal_v2$reason[safety_refusal_v2$obvious_screening == 'Refusal'] <- 'a person who does not want to participate'
safety_refusal_v2$reason[safety_refusal_v2$obvious_screening == 'Pregnant'] <- 'pregnant'
safety_refusal_v2$reason[safety_refusal_v2$obvious_screening == 'Baby'] <- 'A baby that cannot walk yet'
safety_refusal_v2$reason[safety_refusal_v2$obvious_screening == 'Ill'] <- 'A person so ill that they cannot leave the bed'
safety_refusal_v2$reason[safety_refusal_v2$obvious_screening == 'Language'] <- 'does not speak English or Swahili'
safety_refusal_v2$reason[safety_refusal_v2$obvious_screening == 'Witness'] <- 'no witness'
safety_refusal_v2$reason[safety_refusal_v2$ind_thumbprint_status == 0] <- 'not consented or provided their thumbprint'
safety_refusal_v2$reason[safety_refusal_v2$ind_sign_icf_status == 0] <- 'not agree or sign informed consent'
safety_refusal_v2$reason[safety_refusal_v2$minor_assent_status == 0] <- 'minor not sign assent'

# need to filter by visit from clean_safety
safetynew_refusal_v2 <- left_join(safetynew_refusal, clean_safetynew, by=c('PARENT_KEY'='KEY')) %>%
  filter(visit == 'V2')

safetynew_refusal_v2$reason[safetynew_refusal_v2$obvious_screening == 'Refusal'] <- 'a person who does not want to participate'
safetynew_refusal_v2$reason[safetynew_refusal_v2$obvious_screening == 'Pregnant'] <- 'pregnant'
safetynew_refusal_v2$reason[safetynew_refusal_v2$obvious_screening == 'Baby'] <- 'A baby that cannot walk yet'
safetynew_refusal_v2$reason[safetynew_refusal_v2$obvious_screening == 'Ill'] <- 'A person so ill that they cannot leave the bed'
safetynew_refusal_v2$reason[safetynew_refusal_v2$obvious_screening == 'Language'] <- 'does not speak English or Swahili'
safetynew_refusal_v2$reason[safetynew_refusal_v2$obvious_screening == 'Witness'] <- 'no witness'
safetynew_refusal_v2$reason[safetynew_refusal_v2$ind_thumbprint_status == 0] <- 'not consented or provided their thumbprint'
safetynew_refusal_v2$reason[safetynew_refusal_v2$ind_sign_icf_status == 0] <- 'not agree or sign informed consent'
safetynew_refusal_v2$reason[safetynew_refusal_v2$minor_assent_status == 0] <- 'minor not sign assent'

# combine both datasets to be able to make a table of refusal reasons
total_safe_refusal_v2 <- bind_rows(safety_refusal_v2, safetynew_refusal_v2)

# make the table
refusal_reasons_v2 <- total_safe_refusal_v2 %>%
  group_by(reason) %>%
  summarise('Number of refusal people' = n()) %>%
  arrange(reason) %>%
  rename(Reason = reason) %>%
  add_row(Reason = 'total number of people', 'Number of refusal people' = sum(.$'Number of refusal people')) %>%
  mutate('Percent complete' = (as.numeric(`Number of refusal people`)) / as.numeric(nrow(total_safe_refusal_v2)) * 100) %>%
  mutate('Percent complete' = round(`Percent complete`, 2)) %>%
  mutate('Percent complete' = paste0(`Percent complete`, '%'))
```
## Safety targets
```{r target_show}
reactable(target_table, columns = list(), pagination = FALSE)
```

## V2 Numbers
### Overall safety statuses
```{r v2_total_show}
reactable(total_safety_status_v2, columns = list(
  `Percent complete` = colDef(align = "right")
))

# make a note of the real total number of people visited without repeats
if (any(duplicated(total_safety_v2$extid))) {
  cat("Note: Excluding the duplicates, the real total number of people visited is", length(unique(total_safety_v2$extid)), "\n")
} else {
  "Note: There are no duplicates based on extid in the data."
}
```

### in
```{r v2_in_show}
reactable(in_type_v2, columns = list(
  `Percent` = colDef(align = "right")
))
```

### eos
```{r}
reactable(eos_reasons_v2, columns = list(
  `Percent of eos` = colDef(align = 'right')
), pagination = FALSE) #pagination makes the entire table show on one page
```

#### follow up visit
```{r v2_eos_show}
reactable(eos_reasons_followup_v2, columns = list(
  `Percent complete` = colDef(align = 'right')
), pagination = FALSE) #pagination makes the entire table show on one page

# because the table is organised by extid and not reason, some reasons may not appear on the table; therefore the next part will create a line of code that generates a message that says which reason is not appearing. In this by names I mean the reason column.
# Specify the names you want to check for
names_to_check <- c('not wish to continue', 'not agree to safety procedures', 'not resident', 'under weight', 'study drug', 'concom meds', 'severe illness', 'baby under 1 week', 'pregnant', 'other trials', 'visited loa loa', 'spent night at the hospital', 'pregnancy test refusal', 'participant withdrew informed consent', 'died', 'migrated', 'eos in V1')

# Initialize a vector to store names not found
not_found_names <- character(0)

# Check each name
for (name in names_to_check) {
  if (!name %in% eos_reasons_followup_v2$'Reason for eos') {
    not_found_names <- c(not_found_names, name)
  }
}

# Generate a message based on the results (only if names are not found)
if (length(not_found_names) > 0) {
  cat("Note: The reasons (", paste0(not_found_names, collapse = "/ "), ") are not shown because it is not a reason for anyone being missing.")
}
```

#### enrolment visit
```{r eos_enrolment}
reactable(eos_reasons_enrolment_v2, columns = list(
  `Percent complete` = colDef(align = 'right')
), pagination = FALSE) #pagination makes the entire table show on one page

# because the table is organised by extid and not reason, some reasons may not appear on the table; therefore the next part will create a line of code that generates a message that says which reason is not appearing. In this by names I mean the reason column.
# Specify the names you want to check for
names_to_check <- c('not agree to safety procedures', 'not resident', 'under weight', 'study drug', 'concom meds', 'severe illness', 'baby under 1 week', 'pregnant, other trials', 'visited loa loa', 'participant withdrew informed consent')

# Initialize a vector to store names not found
not_found_names <- character(0)

# Check each name
for (name in names_to_check) {
  if (!name %in% eos_reasons_enrolment_v2$'Reason for eos') {
    not_found_names <- c(not_found_names, name)
  }
}

# Generate a message based on the results (only if names are not found)
if (length(not_found_names) > 0) {
  cat("Note: The reasons (", paste0(not_found_names, collapse = ", "), ") are not shown because it is not a reason for anyone being missing.")
}
```

### out
``` {r v2_out_show}
reactable(out_reasons_v2, columns = list(`Percent complete` = colDef(align = 'right')))
```

### refusal
``` {r v2_refusal_show}
reactable(refusal_reasons_v2, columns = list(`Percent complete` = colDef(align = 'right')))
```

## V1 Numbers
### Overall safety statuses
```{r v1_total_show}
reactable(total_safety_status_v1, columns = list(
  `Percent complete` = colDef(align = "right")
))

# make a note of the real total number of people visited without repeats
if (any(duplicated(total_safety_v1$extid))) {
  cat("Note: Excluding the duplicates, the real total number of people visited is", length(unique(total_safety_v1$extid)), "\n")
} else {
  "Note: There are no duplicates based on extid in the data."
}
```

### Safety status by cluster
```{r cluster safety}
element_id <- 'safety-status-by-cluster'

# make the table of safety status by cluster
cluster_status <- total_safety_v1 %>%
  group_by(cluster, safetystatus) %>%
  summarise(number = n()) %>%
  group_by(cluster) %>%
  mutate(percent = paste(round((number / sum(number) * 100), 1), '%')) %>%
  pivot_wider(names_from = safetystatus,
              values_from = c(number, percent),
              values_fill = list(number = 0, percent = '0%')) %>%
  select(cluster, number_eos, percent_eos, number_refusal, percent_refusal, number_out, percent_out, number_in, percent_in) %>%
  mutate(total = sum(number_eos, number_refusal, number_out, number_in))

table <- reactable(cluster_status, columns = list(`percent_refusal` = colDef(align = 'right'),
                                                 `percent_out` = colDef(align = 'right'),
                                                 `percent_in` = colDef(align = 'right'),
                                                 `percent_eos` = colDef(align = 'right')),
                  highlight = TRUE,
                  resizable = TRUE,
                  bordered = TRUE,
                  striped = TRUE,
                  filterable=TRUE,
                  elementId = element_id)

wrap_download(
  table, 
  element_id,
  'safety_status_reason_by_cluster.csv')
```

### eos
```{r v1_eos_show}
reactable(eos_reasons_v1, columns = list(
  `Percent complete` = colDef(align = 'right')
), pagination = FALSE) #pagination makes the entire table show on one page

# because the table is organised by extid and not reason, some reasons may not appear on the table; therefore the next part will create a line of code that generates a message that says which reason is not appearing. In this by names I mean the reason column.
# Specify the names you want to check for
names_to_check <- c('not resident', 'under weight', 'study drug', 'concom meds', 'severe illness', 'baby under 1 week', 'pregnant', 'other trials', 'visited loa loa', 'spent night at the hospital', 'pregnancy test refusal', 'pregnant', 'participant withdrew informed consent', 'not agree to safety procedures')

# Initialize a vector to store names not found
not_found_names <- character(0)

# Check each name
for (name in names_to_check) {
  if (!name %in% eos_reasons_v1$'Reason for eos') {
    not_found_names <- c(not_found_names, name)
  }
}

# Generate a message based on the results (only if names are not found)
if (length(not_found_names) > 0) {
  cat("Note: The reasons (", paste0(not_found_names, collapse = ", "), ") are not shown because it is not a reason for anyone being missing.")
}
```

### out
``` {r v1_out_show}
reactable(out_reasons_v1, columns = list(`Percent complete` = colDef(align = 'right')))
```

### refusal
``` {r v1_refusal_show}
reactable(refusal_reasons_v1, columns = list(`Percent complete` = colDef(align = 'right')))
```

### Absences numbers
```{r absencefirstattempt}
## this will create a table of absent people and tell us whether they had an absence first attempt form filled out or not
total_absent <- bind_rows(total_safe_refusal_v1, 
                     total_safe_out_v1, 
                     total_safe_eos_v1) %>%
  select(extid, safety_status, visit, reason) %>%
  filter(reason == 'absent') %>%
  mutate(group = (ifelse(.$extid %in% absence1stattempt$extid_enter, 'absent with form', 'absent w/out form')))

# make the table
absent_table <- total_absent %>%
  group_by(group) %>%
  summarise('Count' = n()) %>%
  arrange(group) %>%
  add_row(group = 'Total absent', 'Count' = sum(.$'Count')) %>%
  mutate('Percent' = (as.numeric(`Count`)) / as.numeric(nrow(total_absent)) * 100) %>%
  mutate('Percent' = round(`Percent`, 2)) %>%
  mutate('Percent' = paste0(`Percent`, '%')) %>%
  rename('Absent category' = group)

reactable(absent_table, columns = list(`Percent` = colDef(align = 'right')))

# this next part will show the sex and age distribution of those who were absent

distribution <- bind_rows(total_safe_eos_v1, total_safe_out_v1, total_safe_refusal_v1) %>%
  select(extid, safety_status, visit, reason) %>%
  filter(reason == 'absent') 
dist_sex <- left_join(distribution, total_safety_v1, by=c('extid')) %>%
  select(extid, safety_status, sex, todays_date) %>%
  rename(safety_status_use = safety_status,
         sex_use = sex)

dist_age <- left_join(dist_sex, v0_demography, by=c('extid')) %>%
  select(extid, safety_status_use, sex_use, dob, todays_date) %>%
  rename(safety_status = safety_status_use,
         sex = sex_use)

# make raw_dob and todays_date dates so that the appropriate calculation can be made to calculate age
dist_age$dob <- as.Date(dist_age$dob, format = '%Y-%m-%d')
dist_age$todays_date <- as.Date(dist_age$todays_date, format = '%Y-%m-%d')

dist_table <- dist_age %>%
  mutate(age = round(as.numeric(difftime(todays_date, dob, units = "days")) / 365, 2)) %>%
  select(extid, sex, age)

# Create a new column 'age_category' based on 10-year increments
dist_table$age_category <- cut(dist_table$age, breaks = seq(-10, max(dist_table$age) + 10, by = 10), right = FALSE)

# make the appropriate dataframe for a bar plot of ages
dist_age <- dist_table %>%
  group_by(age_category) %>%
  summarise(count = n())

# make the bar plot for age
age_plot <- ggplot(dist_age, aes(x = age_category,
                     y = count,
                     fill = 'black')) +
  geom_bar(stat = 'identity', 
           position = 'dodge',
           show.legend = FALSE) +
  labs(x = 'Ages of Absent Individuals',
       y = 'Count of Absent Individuals') +
  scale_x_discrete(labels = c('below 0', '1-9', '10-19', '20-29', '30-39', '40-49', '50-59', '60-69', '70-79', '80-89')) +
  geom_text(aes(label = count), vjust = 0) +
  theme_minimal()

# make the appropriate data frame for a bar plot of sex
plot_sex <- dist_table %>%
  group_by(sex) %>%
  summarise(count = n())

# make a bar plot of sex
sex_plot <- ggplot(plot_sex, aes(x = sex, y = count, fill = sex)) +
  geom_bar(stat = 'identity', 
           position = 'dodge',
           show.legend = FALSE) +
  labs(x = 'Sex of Absent Individuals',
       y = 'Count of Absent Individuals') +
  geom_text(aes(label = count), vjust = 1.5) +
  theme_minimal()

# Set up the multi-panel layout
par(mfrow = c(1, 2))

# Print the plots side by side
print(age_plot)
print(sex_plot)

```

### Reason to be out by cluster
```{r cluster}
## this will create a table of "Safety Status" and "Reason they are out" by cluster. So we want a column of the clusters and the reason for being out

# need to get the cluster number which is in safety and safetynew or in the df created earlier extid_safety_status_df

element_id <- 'safety_status_reason_out_by_cluster'

cluster <- bind_rows(total_safe_eos_v1, total_safe_out_v1, total_safe_refusal_v1) %>%
  select(extid, safety_status, visit, reason)
cluster <- left_join(cluster, total_safety_v1, by=c('extid')) %>%
  select(extid, cluster, safety_status, reason)

# make the table requested of out reason by cluster
cluster_table <- cluster %>%
  filter(safety_status == 'out') %>%
  select(cluster, reason) %>%
  group_by(cluster, reason) %>%
  summarise(number = n()) %>%
  group_by(cluster) %>%
  mutate(percent = paste(round((number / sum(number) * 100), 1), "%")) %>%
  pivot_wider(names_from = reason, 
              values_from = c(number, percent),
              names_sep = ' that are ',
              values_fill = list(number = 0, percent = "0%")) %>%
  select('cluster', 'number that are A baby that cannot walk yet', 'percent that are A baby that cannot walk yet', 'number that are absent', 'percent that are absent', 'number that are migrated', 'percent that are migrated', 'number that are no witness', 'percent that are no witness', 'number that are pregnant', 'percent that are pregnant', 'number that are A person so ill that they cannot leave the bed', 'percent that are A person so ill that they cannot leave the bed', 'number that are died', 'percent that are died') %>%
  rename('Cluster' = cluster,
         'A baby that cannot walk yet' = 'number that are A baby that cannot walk yet',
         'Absent' = 'number that are absent',
         'Migrated' = 'number that are migrated',
         'No witness' = 'number that are no witness',
         'Pregnant' = 'number that are pregnant',
         'A person so ill they cannot leave bed' = 'number that are A person so ill that they cannot leave the bed',
         'Died' = 'number that are died',
         'Percent of babies that cannot walk' = 'percent that are A baby that cannot walk yet',
         'Percent absent' = 'percent that are absent',
         'Percent migrated' = 'percent that are migrated',
         'Percent no witness' = 'percent that are no witness',
         'Percent pregnant' = 'percent that are pregnant',
         'Percent ill' = 'percent that are A person so ill that they cannot leave the bed',
         'Percent died' = 'percent that are died')

table <- reactable(cluster_table, 
                   columns = list(
                     `Percent migrated` = colDef(align = 'right'),
                     `Percent of babies that cannot walk` = colDef(align = 'right'),
                     `Percent absent` = colDef(align = 'right'),
                     `Percent no witness` = colDef(align = 'right'),
                     `Percent pregnant` = colDef(align = 'right'),
                     `Percent ill` = colDef(align = 'right')),
                      highlight = TRUE,
                      resizable = TRUE,
                      bordered = TRUE,
                      striped = TRUE,
                      filterable=TRUE,
                      elementId = element_id
                   )

wrap_download(
  table, 
  element_id,
  'safety_status_reason_out_by_cluster.csv')

```
